### ISSUE TITLE
Incorrect tool label `dbCAN_sub` on the dbCAN server

### ISSUE THREAD

**Issue by HobnobMancer** [linnabrown/run_dbcan#100]
Hi,

This is an issue with the dbCAN server not the standalone tool, but I'm not 100% sure where to flag the issue.

When using the server to annotate CAZymes, the third tool is now labelled as `dbCAB_sub` not `eCAMI` - I presume it's supposed to be `eCAMI`. You can see if [here](https://bcb.unl.edu/dbCAN2/blast.php).
![dbcanSs](https://user-images.githubusercontent.com/57451458/174295586-6d22bbb0-6511-4a92-a636-05465bbcc044.png)

**Comment by yinlabniu** [comment]
Emma:

We are replacing eCAMI with dbCAN-sub, a new tool that we are developing. The website will be actively updated in the next couple of months as we are experimenting with dbCAN-sub being integrated into the web server.

Yanbin
________________________________
From: Emma Hobbs ***@***.***>
Sent: Friday, June 17, 2022 7:11 AM
To: linnabrown/run_dbcan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [linnabrown/run_dbcan] Incorrect tool label `dbCAN_sub` on the dbCAN server (Issue #100)

Non-NU Email
________________________________

Hi,

This is an issue with the dbCAN server not the standalone tool, but I'm not 100% sure where to flag the issue.

When using the server to annotate CAZymes, the third tool is now labelled as dbCAB_sub not eCAMI - I presume it's supposed to be eCAMI. You can see if here<https://bcb.unl.edu/dbCAN2/blast.php>.
[dbcanSs]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/57451458/174295586-6d22bbb0-6511-4a92-a636-05465bbcc044.png__;!!PvXuogZ4sRB2p-tU!F-SP13ZCj2kmjfJIICTi3mSZRllL5rqg7qnCOKgJ-2LcL1ITmbzA6slg3HZWj7tWfqDar1XKXH9QglQSPxHyJQ$>

**Comment by HobnobMancer** [comment]
Thanks for the quick reply Yanbin!

I see. I presumed it was still `eCAMI` because the website states:
> dbCAN2 meta server integrates three state-of-the-art tools/databases for automated CAZyme annotation:
> [HMMER](http://hmmer.org/) for annotated CAZyme domain boundaries according to the [dbCAN CAZyme domain HMM database](http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/)
> [DIAMOND](https://github.com/bbuchfink/diamond) for fast blast hits in the [CAZy database](http://www.cazy.org/)
> [eCAMI](https://academic.oup.com/bioinformatics/article/36/7/2068/5651014) for simultaneous classification and motif identification for [CAZyme annotation](https://github.com/yinlabniu/eCAMI) (see [here](https://figshare.com/articles/poster/Microbiology_Society_Annual_Conference_2021/14370836/1))  

So anyone that publishes using data generated using your website is going to report the wrong method.

Is `dbCAN_sub` going to implemented into `run_dbcan`?

**Comment by QiweiGe** [comment]
> Thanks for the quick reply Yanbin!
> 
> I see. I presumed it was still `eCAMI` because the website states:
> 
> > dbCAN2 meta server integrates three state-of-the-art tools/databases for automated CAZyme annotation:
> > [HMMER](http://hmmer.org/) for annotated CAZyme domain boundaries according to the [dbCAN CAZyme domain HMM database](http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/)
> > [DIAMOND](https://github.com/bbuchfink/diamond) for fast blast hits in the [CAZy database](http://www.cazy.org/)
> > [eCAMI](https://academic.oup.com/bioinformatics/article/36/7/2068/5651014) for simultaneous classification and motif identification for [CAZyme annotation](https://github.com/yinlabniu/eCAMI) (see [here](https://figshare.com/articles/poster/Microbiology_Society_Annual_Conference_2021/14370836/1))
> 
> So anyone that publishes using data generated using your website is going to report the wrong method.
> 
> Is `dbCAN_sub` going to implemented into `run_dbcan`?

Sorry for the inconvenience; we did some tests on the website today. 
Yes, the dbCAN_sub will be implemented into run_dbcan; if you select dbCAN_sub, it's not using eCAMI anymore, and it gives you the dbCAN_sub result.
