### ISSUE TITLE
Question: why hmmscan and not hmmsearch

### ISSUE THREAD

**Issue by SilasK** [linnabrown/run_dbcan#105]
Would it make sense to use hmmsearch instead of hmmscan? 

http://cryptogenomicon.org/hmmscan-vs-hmmsearch-speed-the-numerology.html

**Comment by linnabrown** [comment]
Thank you so much for the suggestion. Since hmmsearch does not share the same data format as hmmscan, we do not use hmmsearch. We will consider how to replace hmmscan with hmmsearch in an appropriate way in the future.

**Comment by linnabrown** [comment]
Thank you!, We replaced hmmscan with hmmsearch in our new version now (4.1.1), which supports multiple CPUs. Thank you for bringing this out.
