### ISSUE TITLE
docker update - biocontainer for latest version of run_dbcan

### ISSUE THREAD

**Issue by danilodileo** [linnabrown/run_dbcan#107]
Hi all,

are you planning to release a bioconda package for the last version of run_dbcan?

Thanks for your work!

Danilo

**Comment by linnabrown** [comment]
Thanks for reaching out. The latest version is 3.0.7  that Bioconda package already using this version since Aug  30, 2022. Thanks.

**Comment by danilodileo** [comment]
Hi, 
thanks for your reply. I might ask you a silly question but I don't understand why in [quay.io](https://quay.io/search?q=dbcan) website under `biocontainers`folder, the version 2 is the only available, while the version 3.0.7 is under `microbiome-informatics`. It doesn't change the place where the package is stored to me but I can use the last version (I get permission denied error) while this is not happening with the version 2 that it is stored in `biocontainers` folder.

<img width="871" alt="Screenshot 2022-11-10 at 18 58 11" src="https://user-images.githubusercontent.com/78909156/201061665-7b36e632-f4e4-4d02-b216-4bd61fc50293.png">

thanks again, I hope you can help me to understand this issue.

Best,
Danilo

**Comment by linnabrown** [comment]
I have no idea what is biocontainer. But right now our only official package is in the GitHub release (https://github.com/linnabrown/run_dbcan/releases/tag/3.0.7) and Bioconda.

**Comment by danilodileo** [comment]
Do you know how to get docker and singularity containers for dbcan latest version? I am really struggling to find it.

**Comment by linnabrown** [comment]
@danilodileo We currently do not actively maintain the docker version but we mainly focused on github release and Bioconda. We do have the docker for our previous version, please refer to this for the installation (https://github.com/linnabrown/run_dbcan#installation-via-docker). We will update the docker version these days.

**Comment by linnabrown** [comment]
@danilodileo We just updated docker image in docker repository and dockerfile in github repo. Please refer to this part still https://github.com/linnabrown/run_dbcan#installation-via-docker
