### ISSUE TITLE
Formulate overview table from existing output without the need to rerun the analysis

### ISSUE THREAD

**Issue by nohayoussef** [linnabrown/run_dbcan#108]
Good afternoon,
I successfully ran the analysis that resulted in the production of hmm.out, diamond.out, and ecami.out in the output folder. A computer problem (on my end, not with the program) prevented the final overview table from being made. Is there a way I can generate this table with the outputs I have already without the need to go back and repeat the analysis? It took so long to finish.
Thanks

**Comment by linnabrown** [comment]
We did not have this setting. We can add this feature this weekend.

**Comment by nohayoussef** [comment]
> We did not have this setting. We can add this feature this weekend.

That would be very much appreciated. Thank you.

**Comment by linnabrown** [comment]
@nohayoussef Hi, we will update dbcan v3 to dbcan v4 in this weekend, which does not include eCAMI but another new tool so there is no slow issue.

**Comment by linnabrown** [comment]
We now have run_dbcan4.0 which replace eCAMI with dbCAN_sub. Please check our newest code. Thanks a lot!
