### ISSUE TITLE
Question about Docker Hub image versions

### ISSUE THREAD

**Issue by willburden** [linnabrown/run_dbcan#110]
Hi! With the [`haidyi/run_dbcan`](https://hub.docker.com/r/haidyi/run_dbcan/tags) image on Docker Hub, there are currently two tags available:

- `latest`, pushed a month ago
- `3.0.1`, pushed a year ago

It's difficult to determine precisely which version of `run_dbcan` was used to build the `latest` image. The tool itself doesn't seem to have any `--version` flag that would simply print the version and exit. Unfortunately this is preventing us from deploying the tool from the Docker Hub image as we need to know the precise version.

1. Can you let me know which version of run_dbcan is included in the `latest` image?
2. Can it be made easier to determine the version in future? This could mean:
   a) Always providing version-specific tags on Docker Hub as well as `latest`.
   b) Adding a `--version` flag to the command-line tool.

Thanks!

**Comment by linnabrown** [comment]
Thank you for your suggestion. Our official docker version is `latest`, not `3.0.1`. We will remove 3.0.1 tag.

The latest version is version 3.0.7 since the Bioconda team has not integrated our 4.0.0 version which is released recently. We are still waiting for their response.
