### ISSUE TITLE
multithreads options in standalone tool

### ISSUE THREAD

**Issue by chtsai0105** [linnabrown/run_dbcan#113]
Hi - I'm new to the dbcan and want to use it to analyze the proteins predicted from the metaG sample.

I learned that the dbcan combines 3 prediction methods so I guess that the reason to have so many --cpu options in the standalone version. However I found it is very confusing to know how to properly tune it.

Here I listed all the cpu options:
```
--dia_cpu        Number of CPU cores that DIAMOND is allowed to use
--hmm_cpu        Number of CPU cores that HMMER is allowed to use
--dbcan_thread   DBCAN_THREAD
--tf_cpu         tf.hmm Number of CPU cores that HMMER is allowed to use
--stp_cpu        stp.hmm Number of CPU cores that HMMER is allowed to use
```

For my understanding, the meaning of `--dia_cpu` and `--hmm_cpu` is quite clear, which refer to 2 of the prediction methods.

I guess the `--dbcan_thread` is the option to assign how many CPU should be used in the third method? (Since in run_dbcan3 the third tool is eCAMI and there was also option `--eCAMI_jobs` to assign the number of CPU for prediction)

In addition, there are also `--tf_cpu` and `--stp_cpu` under the section "dbCAN-sub parameters". If I have already assign `--dbcan_thread`, will that also be propagated to these 2 options?

**Comment by linnabrown** [comment]
Sorry to confuse you. DBCAN_THREAD is the parameter for the 3rd tool dbcan_sub. Your guess is correct.

--tf_cpu and --stp_cpu are used in CGC cluster finding stage after you finished the three tools (or two or one among those three) CAZyme function annotations. Therefore, dbcan_thread won't be propagated to these 2 options.

I will add more explanations for those parameters. Thanks for brining those questions together.

**Comment by emilyhyde** [comment]
Following up to this question, I am planning on running this on a large scale and cannot determine from testing it myself if there is any overlap in timing for each step, to help plan for thread allocations. For example, if my system has 20 cpus, can I allocate 20 cpus to each of these (--dia_cpu, --hmm_cpu, etc.) or would splitting thread allocation across each one to total 20 cpus be ideal? Thank you very much in advance for your help!
