### ISSUE TITLE
NameError: name 'arr_hotpep' is not defined

### ISSUE THREAD

**Issue by windtalker6** [linnabrown/run_dbcan#12]
dbcan=/mnt/lustre/user/wubin/01.Program/Scripts/02.software/run_dbcan/run_dbcan.py
fa=/mnt/lustre/user/wubin/02.Projects/MetaGenome/02.MetaGenome/01.Stool/06.funcAnno/03.CAZy/test.fa
outdir=/mnt/lustre/user/wubin/02.Projects/MetaGenome/02.MetaGenome/01.Stool/06.funcAnno/03.CAZy/test
dbdir=/mnt/lustre/user/wubin/01.Program/Scripts/03.data/metaGenome/funcAnno/CAZyme

python $dbcan $fa protein  --out_dir $outdir --db_dir $dbdir -t hmmer

===================================================================
the error was like this:

===================================================================

***************************2. HMMER start*************************************************

***************************2. HMMER end***************************************************
python: can't open file 'hmmscan-parser.py': [Errno 2] No such file or directory
Waiting on signalP
SignalP complete
Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "/mnt/lustre/user/wubin/01.Program/Scripts/02.software/run_dbcan/run_dbcan.py", line 553, in <module>
    for i in range(1,len(arr_hotpep)):
NameError: name 'arr_hotpep' is not defined
===================================================================

I have to add the absolute path of "hmmscan-parser.py" in  run_dbcan.py 
which is "/mnt/lustre/user/wubin/01.Program/Scripts/02.software/run_dbcan/hmmscan-parser.py"

and then run "python $dbcan $fa protein  --out_dir $outdir --db_dir $dbdir -t hmmer" again.

I still got the error:
===================================================================
***************************2. HMMER start*************************************************

***************************2. HMMER end***************************************************
Waiting on signalP
SignalP complete
Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "/mnt/lustre/user/wubin/01.Program/Scripts/02.software/run_dbcan/run_dbcan.py", line 553, in <module>
    for i in range(1,len(arr_hotpep)):
NameError: name 'arr_hotpep' is not defined
===================================================================

the Hotpep directory are in the same directory as run_dbcan.py
===================================================================
$ls /mnt/lustre/user/wubin/01.Program/Scripts/02.software/run_dbcan
CGCFinder.py  EscheriaColiK12MG1655.faa  EscheriaColiK12MG1655.gff  Hotpep     log        run_dbcan_backup.py  tools
Dockerfile    EscheriaColiK12MG1655.fna  hmmscan-parser.py          input.fas  README.md  run_dbcan.py
===================================================================

then I have 2 questions:

1. how can I fix the "NameError: name 'arr_hotpep' is not defined" problem
2. I added the absolute path of "hmmscan-parser.py" in  run_dbcan.py, did I do the right thing ?

**Comment by linnabrown** [comment]
Hi, thanks for your feedback and sorry for my late response cause I am going abroad recently.

About this problem, it has the same reason with this case(https://github.com/linnabrown/run_dbcan/issues/13#issuecomment-523047958).

Please refer my answer to another user.  

I recommend you to use dokcer to keep away from this problem.

Thanks for using! 🍡 

Le
