### ISSUE TITLE
doubt on substrate prediction 

### ISSUE THREAD

**Issue by MuthusaravananS** [linnabrown/run_dbcan#122]
I want to predict substrate for my fasta using dbcan_run4 
using following 
run_dbcan 228proteins.fasta protein --out_dir output_228protein -t dbcansub
but I was not able to find substrate in the overview file output, how to get the predicted Substrate in the final output? 
Best regards, 
Muthu

**Comment by yinlabniu** [comment]
We don't write the substrate into the overview file. It will be in the dbsub.out file if you choose to run dbcan-sub.
________________________________
From: Muthusaravanan S ***@***.***>
Sent: Tuesday, July 11, 2023 7:12 AM
To: linnabrown/run_dbcan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [linnabrown/run_dbcan] doubt on substrate prediction (Issue #122)

Non-NU Email
________________________________

I want to predict substrate for my fasta using dbcan_run4
using following
run_dbcan 228proteins.fasta protein --out_dir output_228protein -t dbcansub
but I was not able to find substrate in the overview file output, how to get the predicted Substrate in the final output?
Best regards,
Muthu

**Comment by MuthusaravananS** [comment]
how to run dbcan-sub , can you share the execution command for substrate prediction

**Comment by linnabrown** [comment]
dbcan-sub is integrated in run_dbcan.py https://github.com/linnabrown/run_dbcan/blob/master/dbcan_cli/run_dbcan.py

If you want to run dbcan-sub only, you can only indicate this tool when running our dbcan standalone.
