### ISSUE TITLE
IndexError in CGC-Finder

### ISSUE THREAD

**Issue by Rob-murphys** [linnabrown/run_dbcan#124]
Given the fantastic new capabilities of dbcan 4 I am wanting to rerun some data I previously ran through dbcan 2.  I have installed the latest version of the tool and attempted to run my samples through it but once `CGC-Finder` I get this error:

My running command is:
`run_dbcan $input protein --db_dir $database --out_dir $outdir --hmm_cpu 10 --dia_cpu 10 --tf_cpu 10 --stp_cpu 10 --cluster $locations --cgc_substrate`
```
Clearing query masking...  [0.014s]
Computing alignments... Loading trace points...  [0.092s]
Sorting trace points...  [0.025s]
Computing alignments...  [20.672s]
Deallocating buffers...  [0s]
Loading trace points...  [0s]
 [20.799s]
Deallocating reference...  [0s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0s]
Deallocating queries...  [0.014s]
Total time = 51.184s
Reported 37268 pairwise alignments, 37268 HSPs.
37268 queries aligned.

Traceback (most recent call last):
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/run_dbcan_4/bin/run_dbcan", line 10, in <module>
    sys.exit(cli_main())
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/run_dbcan_4/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 883, in cli_main
    run(inputFile=args.inputFile, inputType=args.inputType, cluster=args.cluster, dbCANFile=args.dbCANFile,
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/run_dbcan_4/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 584, in run
    gene = row[1]
IndexError: list index out of range
```

I included a few of the lines that come before it in case that is helpful. 
Any idea how I can solve this issue?

**Comment by Rob-murphys** [comment]
[sample data.zip](https://github.com/linnabrown/run_dbcan/files/12195546/sample.data.zip)
Here is a sample of the data

**Comment by linnabrown** [comment]
thx will do this in the weekend

**Comment by Rob-murphys** [comment]
Many thanks :)
I am really excited to see the predicted substrates and gene families!

**Comment by linnabrown** [comment]
Thx

**Comment by linnabrown** [comment]
Sorry I forgot to resolve it. Let me do this today night.

**Comment by Rob-murphys** [comment]
Hey @linnabrown, I have tried running the tool on subsets of the data and after freshly reinstalling and still get the same error. unfortunately.

**Comment by yinlabniu** [comment]
Hi Rob,  the problem might be from the location file (gff), specified by --cluster $locations. It might be that it's not in an acceptable format. you just shared your the protein seq file (faa), can you also share the gff file for us to look at where the problem is?

**Comment by Rob-murphys** [comment]
Hi @yinlabniu, here is the associated gff file 😄 
[sample_data_gff.zip](https://github.com/linnabrown/run_dbcan/files/12483299/sample_data_gff.zip)

**Comment by yinlabniu** [comment]
okay, your gff file is clearly not in gff format. You may see https://www.ncbi.nlm.nih.gov/genbank/genomes_gff/ or https://www.youtube.com/watch?v=hiRXtxcTn_I for the gff format.

**Comment by Rob-murphys** [comment]
Opps, I forgot to request gff from prokka but thought I had. My bad!
