### ISSUE TITLE
dbCAN-sub error 

### ISSUE THREAD

**Issue by chandnisidhu** [linnabrown/run_dbcan#126]
Hi,

I'm encountering an error while trying to run dbCAN-sub, and it appears to be related to the output generation. Any assistance you could provide would be greatly appreciated.

Best,

Chandni

Error:

`$run_dbcan compiled.faa protein --out_dir output_test -t dbcansub

***************************3. dbCAN_sub start***************************************************

ID count: 195
total time: 120.3644289970398

***************************3. dbCAN_sub end***************************************************

Traceback (most recent call last):
  File "/Users/csidhu/miniconda3/envs/run_dbcan/bin/run_dbcan", line 10, in <module>
    sys.exit(cli_main())
  File "/Users/csidhu/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 883, in cli_main
    run(inputFile=args.inputFile, inputType=args.inputType, cluster=args.cluster, dbCANFile=args.dbCANFile,
  File "/Users/csidhu/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 290, in run
    with open(f"{outPath}dbsub.out") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_test/dbsub.out'`

**Comment by linnabrown** [comment]
Hi Chandni, 
Thanks for using our tool. I found that you only specify using dbcansub right? If you did not specify the tool, did you still confront this issue? If possible, could you please provide ur input data to us? We would like to replicate this issue with ur data on our end. Thanks a lot!

**Comment by chandnisidhu** [comment]
Hi,

The error has been resolved. There was some issue in our server.

Thank you for your prompt response.

Best,

Chandni
