### ISSUE TITLE
Interpretation of output results

### ISSUE THREAD

**Issue by MonaLiu421** [linnabrown/run_dbcan#127]
Dear linnabrown,

Thank you for developing such a good software. I have encountered some result files that were generated during the use process. However, I am uncertain about the exact meaning and significance of these files. I believe that understanding their purpose would greatly benefit my project and contribute to its overall success. Can you explain to me the meaning of the three files respectively?
first one:blastp.out
![image](https://github.com/linnabrown/run_dbcan/assets/45484925/bf27ab35-8a38-4f6f-8200-e3428a28a274)
second one:dbsub.out
![image](https://github.com/linnabrown/run_dbcan/assets/45484925/5efb32d8-ecdc-4b90-b4cf-69e48ac18a2d)
third one:sub.prediction.out
![image](https://github.com/linnabrown/run_dbcan/assets/45484925/cd2f3193-9096-4ba4-8780-086cb8ca6332)

Warm regards,
Mona

**Comment by MonaLiu421** [comment]
hi, Yanbin.Thank you for your prompt reply.I get it.
other questions, can both CAZyme substrate prediction and  substrate prediction for CGCs be used for subsequent analysis? and what's the differences between CGC and PUL?

**Comment by yinlabniu** [comment]
CGCs are computer predicted gene clusters (see our dbCAN2 paper https://academic.oup.com/nar/article/46/W1/W95/4996582), while PULs are CGCs with experimentally verified substrates. PULs are usually co-regulated/co-expressed. Some CGCs might be falsely predicted and will never become PULs.

Not all CAZymes are located in CGCs/PULs, so predicting substrates for CAZymes might be more broadly applicable. However, according to our dbCAN3 paper (table 1: https://academic.oup.com/nar/article/51/D1/D557/6833251), about 50% CAZymes in a bacterial genomes are in CGCs, so predicting substrates for CGCs are also very useful and tend to be more accurate (table 1: https://academic.oup.com/nar/article/51/W1/W115/7147496).

Yanbin


________________________________

**Comment by MonaLiu421** [comment]
Thank you for your prompt reply. So the PUL corresponding to the CGC predicted in the third file sub.prediction.out , can i consider it has been verified by experiments?

**Comment by yinlabniu** [comment]
No, PULs are verified, but CGCs are not. The file provides you the substrate prediction for CGCs based on the PUL match.
________________________________

**Comment by MonaLiu421** [comment]
If I want to know the specific PULs, which file should I go to find it?

**Comment by yinlabniu** [comment]
https://bcb.unl.edu/dbCAN_PUL/
________________________________

**Comment by MonaLiu421** [comment]
ok,thanks a millon.
