### ISSUE TITLE
Explanation for docker command

### ISSUE THREAD

**Issue by blueevee** [linnabrown/run_dbcan#128]
Hi! I'm trying to execute dbcan on docker and getting in some trouble understanding the command.
I am not an expert on anything of this, but I already sold out all my ideas.
I understand that I need to put my host path to bind a volume in docker path, I need also my file and a output directory so my last attempt was this:
 `docker run --name dbcan2 -v C:/Users/evelyn.ferreira/Documents/eevee/estudos/FACULDADE/TCC/plasticome/plasticome/genomes:/genomes -it haidyi/run_dbcan:latest python run_dbcan.py /genomes/123.faa prok --out_dir /genomes`
 But I am getting this error, like it can't create the output folder and can't find the file to execute:
 
![image](https://github.com/linnabrown/run_dbcan/assets/38510495/8f937843-2714-43b7-8f81-c6ae77d1d7af)

I really want to understand how I must have to put the input file, I already try the absolute host path, and relative path, but I'm always getting the error "No such file or directory". My unique successful attempt was when use the sample file "EscheriaColiK12MG1655.fna", but I really think that its using the example file inside the container and not use my created volume folder :/
docker container run -ti --name dbcan-2 -v `C:/Users/evelyn.ferreira/Documents/eevee/estudos/FACULDADE/TCC/plasticome/plasticome/genomes:/app/genomes haidyi/run_dbcan:latest EscheriaColiK12MG1655.fna protein --out_dir teste_2`

Just to show that my volume is inside the container too:
![image](https://github.com/linnabrown/run_dbcan/assets/38510495/8cc134ed-f9e9-42bb-a1c6-a65a8c06a83a)

I really appreciate some help with it!

**Comment by linnabrown** [comment]
Sorry I will have long drive tmr. I will respond I next week thx

**Comment by blueevee** [comment]
Oh thank you very much, I hope to hear from you soon good drive!

**Comment by blueevee** [comment]
I rewrote my function and changed my files, and now it works for me!!!
