### ISSUE TITLE
Multiple errors finding sequence files 

### ISSUE THREAD

**Issue by singhbhavya** [linnabrown/run_dbcan#13]
Hi there! I've been trying to use dbcan, but have encountered a few errors. Due to the nature of my server, I unfortunately cannot use docker, so I tried to set up everything myself. 

This is what I ran:
`python /home/bsingh/bin/run_dbcan/run_dbcan.py megahit_SA613/final.contigs.fa meta --out_dir dbcan/ --db_dir /home/bsingh/bin/dbcan_db --dia_cpu 40 --hmm_cpu 40 --tf_cpu 40 --stp_cp 40`

These are some of the errors I'm receiving:

```
**ERROR: You missed some parameters for input**
USAGE: ./FragGeneScan -s [seq_file_name] -o [output_file_name] -w [1 or 0] -t [train_file_name] (-p [thread_num])

**cp: cannot stat 'dbcan/fragGeneScan.faa': No such file or directory**

***************************1. DIAMOND start*************************************************


***************************2. HMMER start*************************************************


diamond v0.9.25.126 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 40
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: dbcan
Opening the database...  [5.8e-05s]
#Target sequences to report alignments for: 1
**Opening the input file... No such file or directory**
 [0.000124s]
Error: Error opening file dbcan/uniInput

**Error: Failed to open sequence file dbcan/uniInput for reading**

/bin/sh: dbcan/uniInput: No such file or directory
Traceback (most recent call last):
  File "/home/bsingh/bin/run_dbcan/run_dbcan.py", line 171, in <module>
    count_per_file = count / numThreads                                                #number of genes per core
ZeroDivisionError: division by zero
ESCkbsingh@yeats-admin:~/aman/megahit_SA613ESC\[bsingh@yeats-admin:6 megahit_SA613]$ flag provided but not defined: -t
flag provided but not defined: -t
Usage of signalp:
Usage of signalp:
```

**Comment by singhbhavya** [comment]
Hi there - I ended up trying docker on my person computer, and have continued to receive errors.

This is what I ran:
`docker run --rm --name dbcan -v ~/result:/result -it haidyi/run_dbcan:latest python run_dbcan.py ./megahit_final.contigs.fa meta --out_dir /result/output`

This is the error I received:

```
ERROR: You missed some parameters for input
USAGE: ./FragGeneScan -s [seq_file_name] -o [output_file_name] -w [1 or 0] -t [train_file_name] (-p [thread_num])

       Mandatory parameters
       [seq_file_name]:    sequence file name including the full path
       [output_file_name]: output file name including the full path
       [1 or 0]:           1 if the sequence file has complete genomic sequences
                           0 if the sequence file has short sequence reads
       [train_file_name]:  file name that contains model parameters; this file should be in the "train" directory
                           Note that four files containing model parameters already exist in the "train" directory
                           [complete] for complete genomic sequences or short sequence reads without sequencing error
                           [sanger_5] for Sanger sequencing reads with about 0.5% error rate
                           [sanger_10] for Sanger sequencing reads with about 1% error rate
                           [454_5] for 454 pyrosequencing reads with about 0.5% error rate
                           [454_10] for 454 pyrosequencing reads with about 1% error rate
                           [454_30] for 454 pyrosequencing reads with about 3% error rate
                           [illumina_5] for Illumina sequencing reads with about 0.5% error rate
                           [illumina_10] for Illumina sequencing reads with about 1% error rate

       Optional parameter
       [thread_num]:       the number of threads used by FragGeneScan; default is 1 thread.
cp: cannot stat '/result/output/fragGeneScan.faa': No such file or directory
***************************1. DIAMOND start*************************************************


***************************2. HMMER start*************************************************



Error: Failed to open sequence file /result/output/uniInput for reading

diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

/bin/sh: 1: cannot open /result/output/uniInput: No such file
#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11Traceback (most recent call last):
  File "run_dbcan.py", line 171, in <module>
    count_per_file = count / numThreads                                                #number of genes per core
ZeroDivisionError: division by zero

```

Please let me know if you are able to spot what I'm doing wrong!!! Any and all help is greatly appreciated. Thank you for your time.

**Comment by linnabrown** [comment]
Sorry, recently I was starting new school semester and was busying a lot of stuffs.
To keep away from this problem, I think you need to keep your command "python run_dbcan.py ..." and python script "run_dbcan.py" consistense. 
What's more, the problem is caused by FragGeneScan program. If you set up FragGeneScan well, and execute the commands consistently in the same root, this problem may not happen.

Thanks for you patience and sorry for my late response.

Le

**Comment by singhbhavya** [comment]
Hi! Thanks for your response! I don't think there is a problem with the FragGeneScan installation, since it seems to work well independently, but doesn't work through dbcan.

I suspect that there has been an update to the FragGeneScan program, which may have changed the required parameters when running it - this might be why we see `**ERROR: You missed some parameters for input**`

^Because of this, FragGeneScan doesn't run, and hence the fragGeneScan.faa file is not created, meaning that the uniInput file ins't created either. There seems to be some problem in the part of the script that formats the input for fragGeneScan.

**Comment by linnabrown** [comment]
Yes

> Hi! Thanks for your response! I don't think there is a problem with the FragGeneScan installation, since it seems to work well independently, but doesn't work through dbcan.
> 
> I suspect that there has been an update to the FragGeneScan program, which may have changed the required parameters when running it - this might be why we see `**ERROR: You missed some parameters for input**`
> 
> ^Because of this, FragGeneScan doesn't run, and hence the fragGeneScan.faa file is not created, meaning that the uniInput file ins't created either. There seems to be some problem in the part of the script that formats the input for fragGeneScan.

Maybe, in this github, I also put FragGeneScan1.30, an old version in tools/ directory. Maybe you can try the old one "https://github.com/linnabrown/run_dbcan/tree/master/tools". Thanks!

Le
