### ISSUE TITLE
dbCAN_sub error (#2)

### ISSUE THREAD

**Issue by jgrembi** [linnabrown/run_dbcan#130]
I can't get the test example for E.coli to run.  It errors in dbCAN_sub due to an index error as shown below.
Am I doing something wrong?
Thanks,
Jess

command: 
run_dbcan EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655 --tools all

output:
***************************1. DIAMOND start*************************************************
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: output_EscheriaColiK12MG1655
#Target sequences to report alignments for: 1
Opening the database...  [0.201s]
Database: /oak/stanford/groups/relman/public/databases/cazyme_db/CAZy (type: Diamond database, sequences: 2428817, letters: 1157024505)
Block size = 2000000000
Building query seed set...  [0.092s]
Algorithm: Query-indexed
Building query histograms...  [0.018s]
Seeking in database...  [0s]
Loading reference sequences...  [3.284s]
Initializing temporary storage...  [0.009s]
Building reference histograms...  [10.068s]
Allocating buffers...  [0s]
Processing query block 1, reference block 1/1, shape 1/2.
Building reference seed array...  [5.787s]
Building query seed array...  [0.014s]
Computing hash join...  [1.777s]
Searching alignments...  [6.49s]
Deallocating memory...  [0s]
Processing query block 1, reference block 1/1, shape 2/2.
Building reference seed array...  [5.556s]
Building query seed array...  [0.029s]
Computing hash join...  [1.317s]
Searching alignments...  [6.999s]
Deallocating memory...  [0s]
Deallocating buffers...  [0.193s]
Clearing query masking...  [0s]
Computing alignments... Loading trace points...  [0.106s]
Sorting trace points...  [0.034s]
Computing alignments...  [13.294s]
Deallocating buffers...  [0.015s]
Loading trace points...  [0s]
 [13.516s]
Deallocating reference...  [0.198s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0s]
Deallocating queries...  [0s]
Total time = 55.595s
Reported 197 pairwise alignments, 197 HSPs.
197 queries aligned.

***************************1. DIAMOND end***************************************************
***************************2. HMMER start*************************************************
***************************2. HMMER end***************************************************
***************************3. dbCAN_sub start***************************************************
ID count: 4319
Traceback (most recent call last):
  File "/home/users/jgrembi/miniconda3/envs/run_dbcan/bin/run_dbcan", line 10, in <module>
    sys.exit(cli_main())
  File "/home/users/jgrembi/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 883, in cli_main
    run(inputFile=args.inputFile, inputType=args.inputType, cluster=args.cluster, dbCANFile=args.dbCANFile,
  File "/home/users/jgrembi/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 252, in run
    split_uniInput('%suniInput'%outPath,dbcan_thread,outPath,dbDir,hmm_eval,hmm_cov)
  File "/home/users/jgrembi/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 95, in split_uniInput
    hmm_parser_output = hmmscan_parser.run("%sd%s"%(outPath,m), eval_num=hmm_eval, coverage=hmm_cov)
  File "/home/users/jgrembi/miniconda3/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/hmmscan_parser.py", line 42, in run
    row.append(float(int(row[6])-int(row[5]))/int(row[1]))
IndexError: list index out of range

**Comment by linnabrown** [comment]
I did not confront this issue and I used the totally the same command

(run_dbcan) ➜  run_dbcan git:(dbcan-proto) ✗ run_dbcan EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655 --tools dbcansub --hmm_cpu 12


***************************3. dbCAN_sub start***************************************************


ID count: 4319
1e-15 0.35
GH23_e734.hmm|GH23:3967|4.2.2.n1:8      150     NC_000913.3_1163        204     1.5e-69 1       148     53      200     0.98
GH37_e6.hmm|GH37:7900|3.2.1.28:18       476     NC_000913.3_1167        566     4.8e-224        1       474     58      530     0.9936974789915967
GH13_e137.hmm|GH13_18:228|GH13:5|2.4.1.352:2    342     NC_000913.3_1285        560     1e-179  1       342     83      424     0.9970760233918129
GH109_e7.hmm|GH109:31   390     NC_000913.3_1291        352     4.4e-19 2       147     10      156     0.3717948717948718
GT19_e17.hmm|GT19:7713|2.4.1.182:13     358     NC_000913.3_177 383     1e-174  1       358     10      367     0.9972067039106145
CBM50_e567.hmm|CBM50:3868       42      NC_000913.3_1834        441     2e-23   1       42      99      140     0.9761904761904762
GT4_e1752.hmm|GT4:31    141     NC_000913.3_1998        373     2e-52   1       138     203     338     0.9716312056737588
GT4_e731.hmm|GT4:130    149     NC_000913.3_2010        407     1.1e-69 1       145     225     369     0.9664429530201343
GT4_e2254.hmm|GT4:11    152     NC_000913.3_2016        408     4.1e-50 3       148     230     375     0.9539473684210527
GH3_e1.hmm|GH3:5872|3.2.1.21:20|3.2.1.-:6|GH16:4|CBM6:2|GH144:1 222     NC_000913.3_2100        756     8.2e-100        2       221     90      309     0.9864864864864865
GT83_e0.hmm|GT83:3973|2.4.2.43:13       513     NC_000913.3_2225        551     2.3e-249        3       513     8       517     0.9941520467836257
GT2_e2523.hmm|GT2:233   162     NC_000913.3_2319        307     6.4e-84 1       162     5       166     0.9938271604938271
GH23_e225.hmm|GH23:4469|4.2.2.n1:1      154     NC_000913.3_2525        519     7.1e-82 1       153     298     450     0.987012987012987
GH13_e166.hmm|GH13_27:44        316     NC_000913.3_2613        264     3e-21   116     315     23      238     0.629746835443038
CBM50_e486.hmm|CBM50:11431|GH73:1|CE4:1|GH25:1  43      NC_000913.3_2694        380     1.2e-22 1       42      124     165     0.9534883720930233
GH23_e259.hmm|GH23:688  121     NC_000913.3_2806        125     6.2e-73 1       116     5       119     0.9504132231404959
GH1_e0.hmm|GH1:9150|3.2.1.86:26|3.2.1.23:2|3.2.1.21:1   472     NC_000913.3_2850        478     3.7e-249        2       472     6       475     0.9957627118644068
GH2_e92.hmm|GH2:6387|3.2.1.23:41|CBM67:1|CBM32:1        861     NC_000913.3_3016        1031    0       3       861     28      887     0.9965156794425087
GH63_e1.hmm|GH63:1941|3.2.1.20:9|3.2.1.84:9     774     NC_000913.3_3020        784     0       2       774     8       781     0.9974160206718347
CE9_e34.hmm|CE9:1668|3.5.1.25:2|3.5.1.80:2      366     NC_000913.3_3070        152     1.3e-77 220     366     1       147     0.3989071038251366
GT51_e0.hmm|GT51:5325|2.4.1.129:10      165     NC_000913.3_3141        243     5.1e-88 1       164     63      227     0.9878787878787879
GH18_e193.hmm|GH18:646|CBM5:643|CBM73:11|3.2.1.14:10|CBM13:1|CBM12:1    188     NC_000913.3_3267        898     2.3e-109        1       188     607     794  0.9946808510638298
GT51_e130.hmm|GT51:5094|2.4.1.129:12    176     NC_000913.3_3325        851     6.7e-93 1       176     55      230     0.9943181818181818
GT2_e2022.hmm|GT2:522|2.4.1.12:6|2.4.1.-:1      352     NC_000913.3_3464        873     9e-106  91      265     275     450     0.4943181818181818
GT2_e2022.hmm|GT2:522|2.4.1.12:6|2.4.1.-:1      352     NC_000913.3_3464        873     6.7e-61 78      286     434     690     0.5909090909090909
CE1_e38.hmm|CE1:175     268     NC_000913.3_348 278     7e-18   2       149     23      185     0.5485074626865671
GH73_e253.hmm|GH73:3299 123     NC_000913.3_3503        275     2.2e-67 1       123     146     268     0.991869918699187
GH13_e62.hmm|GH13_19:166|CBM26:16|CBM25:10|CBM74:4|GH13:2|3.2.1.-:1|CBM48:1|3.2.1.1:1   378     NC_000913.3_3504        677     2.5e-194        1       377  227      595     0.9947089947089947
GT73_e2.hmm|GT73:871|2.4.99.-:10        239     NC_000913.3_3559        284     4.3e-137        1       238     19      256     0.9916317991631799
GT8_e147.hmm|GT8:1945|2.4.1.-:10|2.4.1.44:3|2.4.1.58:1  251     NC_000913.3_3562        340     1.9e-118        4       251     29      277     0.9840637450199203
GT4_e1251.hmm|GT4:177|2.4.1.-:2 150     NC_000913.3_3566        375     1.4e-70 2       146     195     339     0.96
GT30_e0.hmm|GT30:6984|2.4.99.-:25|GT2:1 177     NC_000913.3_3568        426     1.6e-80 1       176     35      211     0.9887005649717514
CE14_e27.hmm|CE14:619   106     NC_000913.3_357 186     3.7e-20 1       106     21      131     0.9905660377358491
GT26_e141.hmm|GT26:4099|2.4.1.-:12      170     NC_000913.3_3722        247     1.1e-93 2       170     64      232     0.9882352941176471
GH31_e85.hmm|GH31:2083|3.2.1.199:9      440     NC_000913.3_3796        679     2.9e-223        2       439     230     666     0.9931818181818182
GH24_e32.hmm|GH24:2579|3.2.1.17:8       125     NC_000913.3_544 166     8.4e-68 2       125     34      157     0.984
CE11_e22.hmm|CE11:9240|3.5.1.108:18     272     NC_000913.3_93  306     1.3e-133        1       271     5       276     0.9926470588235294
AA6_e2.hmm|AA6:22       195     NC_000913.3_980 199     5.1e-71 2       193     5       193     0.9794871794871794

GT2_e285.hmm|GT2:630    347     NC_000913.3_1023        838     1e-156  4       342     235     573     0.9740634005763689
GH73_e114.hmm|GH73:3220|3.2.1.-:3       136     NC_000913.3_1054        314     9.6e-67 1       136     160     295     0.9926470588235294
GH65_e4.hmm|GH65:1853|2.4.1.230:11      386     NC_000913.3_1292        756     5.5e-181        1       385     299     674     0.9948186528497409
GH24_e98.hmm|GH24:3855  140     NC_000913.3_1530        178     9.6e-83 1       140     29      168     0.9928571428571429
GH4_e24.hmm|GH4:7862|3.2.1.86:16        179     NC_000913.3_1712        451     9.4e-90 1       178     7       185     0.9888268156424581
GH13_e245.hmm|GH13_5:159|GH13:3|3.2.1.1:2       342     NC_000913.3_1901        496     1.4e-191        2       342     33      374     0.9941520467836257
GT113_e0.hmm|GT113:182|2.4.1.-:1        321     NC_000913.3_2000        331     8.1e-96 2       320     12      323     0.9906542056074766
GH23_e819.hmm|GH23:3899|CBM50:3878      143     NC_000913.3_202 407     3.1e-76 1       143     56      198     0.993006993006993
CBM50_e338.hmm|CBM50:4180|GH23:4153     43      NC_000913.3_202 407     2.4e-21 1       42      298     338     0.9534883720930233
CBM50_e338.hmm|CBM50:4180|GH23:4153     43      NC_000913.3_202 407     2.4e-20 1       42      357     396     0.9534883720930233
GT4_e1042.hmm|GT4:40    71      NC_000913.3_2023        406     6.7e-45 1       71      288     358     0.9859154929577465
GT2_e1464.hmm|GT2:42    127     NC_000913.3_2025        280     3.6e-75 1       126     9       134     0.984251968503937
GT2_e978.hmm|GT2:251    165     NC_000913.3_2222        323     1e-80   1       163     12      174     0.9818181818181818
CBM50_e391.hmm|CBM50:1681       49      NC_000913.3_2620        150     6.4e-31 1       49      100     148     0.9795918367346939
GH43_e285.hmm|GH43_11:2705|3.2.1.37:21|GH43:7|3.2.1.55:3|GH43_12:2|3.2.1.-:1    292     NC_000913.3_267 537     2.3e-138        1       292     4       304  0.9965753424657534
CBM91_e24.hmm|CBM91:3225|GH43_11:3213|GH43_12:1|GH43:1  200     NC_000913.3_267 537     6e-82   1       199     332     535     0.99
GH102_e2.hmm|GH102:4353|4.2.2.n1:8      134     NC_000913.3_2765        366     1.8e-70 1       134     127     258     0.9925373134328358
CBM50_e486.hmm|CBM50:11431|GH73:1|CE4:1|GH25:1  43      NC_000913.3_2814        252     2.5e-21 1       42      43      84      0.9534883720930233
GH23_e150.hmm|GH23:4464|4.2.2.n1:2      149     NC_000913.3_2908        360     1.8e-73 2       148     208     354     0.9798657718120806
AA3_e57.hmm|AA3_2:11    532     NC_000913.3_305 557     1.9e-205        1       532     3       533     0.9981203007518797
GH77_e27.hmm|GH77:4919|GH13_26:95|2.4.1.25:11|GT35:1    540     NC_000913.3_3345        695     9.5e-274        1       539     149     685     0.9962962962962963
GT35_e0.hmm|GT35:17065|2.4.1.1:158|GH77:18|GH13_39:1    712     NC_000913.3_3356        816     0       1       711     102     811     0.9971910112359551
GT5_e31.hmm|GT5:5296|2.4.1.21:29        473     NC_000913.3_3357        478     6.3e-215        1       472     3       474     0.9957716701902748
CBM48_e3.hmm|CBM48:14267|GH13_11:14161|3.2.1.68:75|GH13:59|GH77:38|2.4.1.25:4|GH13_10:2|GH13_36:1|3.2.1.-:1     101     NC_000913.3_3359        658     5.1e-41       4       96      10      101     0.9108910891089109
GH13_e48.hmm|GH13_11:3001|CBM48:2819|GH13:35|GH77:23|3.2.1.68:15|GH13_10:3|3.2.1.-:1    358     NC_000913.3_3359        658     6.2e-157        3       356  173      522     0.9860335195530726
CBM48_e2.hmm|CBM48:14087|GH13_9:14033|2.4.1.18:57|GH77:8|GH13:5|GT5:2|GH13_3:1|GH0:1    100     NC_000913.3_3360        729     7.9e-17 6       90      22   112      0.84
CBM48_e2.hmm|CBM48:14087|GH13_9:14033|2.4.1.18:57|GH77:8|GH13:5|GT5:2|GH13_3:1|GH0:1    100     NC_000913.3_3360        729     1.5e-28 6       89      122  218      0.83
GH13_e200.hmm|GH13_9:2874|CBM48:2782|2.4.1.18:14|GH77:10|GH13:7|GH13_3:5|GH0:1|GT5:1|GH13_1:1   301     NC_000913.3_3360        729     1.3e-159        1    300      275     574     0.9933554817275747
GH2_e92.hmm|GH2:6387|3.2.1.23:41|CBM67:1|CBM32:1        861     NC_000913.3_337 1025    0       3       861     40      917     0.9965156794425087
GT9_e84.hmm|GT9:7143|2.4.99.-:11|GT2:1  263     NC_000913.3_3555        349     8.7e-117        5       241     66      307     0.8973384030418251
GT4_e1207.hmm|GT4:40|2.4.1.-:1  147     NC_000913.3_3563        360     5.9e-70 2       145     179     322     0.9727891156462585
GH31_e31.hmm|GH31:4050|3.2.1.177:12     431     NC_000913.3_3591        773     6.7e-239        1       430     240     669     0.9953596287703016
GH4_e4.hmm|GH4:5108|3.2.1.122:13        177     NC_000913.3_3617        213     7.7e-94 1       177     7       183     0.9943502824858758
CBM48_e68.hmm|CBM48:192|CE0:190|CE6:12|GH10:3|CE1:2|GH62:1|3.1.1.73:1|3.2.1.55:1|3.2.1.8:1      61      NC_000913.3_3654        390     9.6e-16 2       59   49       110     0.9344262295081968
CE1_e22.hmm|CE1:6|CBM48:2|CE0:2 206     NC_000913.3_3654        390     4.6e-41 3       205     160     383     0.9805825242718447
GH1_e85.hmm|GH1:13226|3.2.1.86:49|3.2.1.21:4|3.2.1.37:1 470     NC_000913.3_3656        471     3.5e-223        1       469     4       459     0.9957446808510638
GH4_e0.hmm|GH4:3065|3.2.1.22:13 181     NC_000913.3_4037        452     9e-107  1       181     7       187     0.994475138121547
GH109_e7.hmm|GH109:31   390     NC_000913.3_4191        373     1.7e-17 3       192     3       184     0.4846153846153846
GH23_e96.hmm|GH23:3929|4.2.2.n1:10      127     NC_000913.3_4309        646     1.2e-66 1       126     497     622     0.984251968503937
GH38_e0.hmm|GH38:1275   259     NC_000913.3_715 878     4.1e-147        1       259     7       265     0.9961389961389961
CE8_e3.hmm|CE8:3130     331     NC_000913.3_749 428     3.1e-207        1       331     91      421     0.9969788519637462
GT28_e46.hmm|GT28:8561|2.4.1.227:11     160     NC_000913.3_87  356     2e-65   1       159     185     341     0.9875

CE4_e321.hmm|CE4:3543|GH153:3495|3.5.1.-:8|3.2.1.-:8|GT2:1      170     NC_000913.3_1000        673     1.4e-72 2       170     104     272     0.9882352941176471
GH153_e1.hmm|GH153:2729|CE4:2716|3.5.1.-:7|3.2.1.-:7    349     NC_000913.3_1000        673     1.8e-167        1       349     315     665     0.997134670487106
GH3_e19.hmm|GH3:6438|3.2.1.52:16        223     NC_000913.3_1079        342     2.1e-109        2       223     56      278     0.9910313901345291
CBM50_e118.hmm|CBM50:9  44      NC_000913.3_1085        320     2.7e-17 4       43      51      90      0.8863636363636364
AA1_e20.hmm|AA1:10      461     NC_000913.3_118 517     2.6e-29 3       461     75      512     0.9934924078091106
CE4_e2.hmm|CE4:695|3.5.1.-:1    140     NC_000913.3_125 410     3.4e-27 2       139     229     368     0.9785714285714285
GT51_e28.hmm|GT51:6681|2.4.1.129:11     172     NC_000913.3_144 845     7.3e-84 2       171     211     380     0.9825581395348837
GH2_e29.hmm|GH2:3674|3.2.1.31:89|GH31:1 578     NC_000913.3_1594        604     3.8e-269        2       578     9       588     0.9965397923875432
GT20_e1.hmm|GT20:8450|2.4.1.15:96       473     NC_000913.3_1874        475     5.1e-181        9       471     2       454     0.9767441860465116
GT2_e1702.hmm|GT2:5     136     NC_000913.3_1997        158     1.3e-73 1       130     5       135     0.9485294117647058
GT2_e1154.hmm|GT2:59    129     NC_000913.3_2021        249     4.6e-53 1       127     5       134     0.9767441860465116
GH25_e19.hmm|GH25:1217  167     NC_000913.3_2068        273     1.3e-99 1       167     71      246     0.9940119760479041
GT51_e71.hmm|GT51:5520  166     NC_000913.3_2486        758     4.4e-80 1       165     50      213     0.9879518072289156
GH103_e0.hmm|GH103:4244|4.2.2.n1:10     291     NC_000913.3_2652        397     1.1e-141        1       290     100     390     0.993127147766323
GH1_e85.hmm|GH1:13226|3.2.1.86:49|3.2.1.21:4|3.2.1.37:1 470     NC_000913.3_2667        475     1e-230  1       470     4       471     0.997872340425532
GT35_e0.hmm|GT35:17065|2.4.1.1:158|GH77:18|GH13_39:1    712     NC_000913.3_3346        798     0       1       711     92      796     0.9971910112359551
GH37_e6.hmm|GH37:7900|3.2.1.28:18       476     NC_000913.3_3450        550     3.1e-213        1       475     73      545     0.9957983193277311
GH8_e0.hmm|GH8:4312|3.2.1.4:20|3.2.1.6:1        326     NC_000913.3_3462        369     9.1e-150        1       326     26      344     0.9969325153374233
GT2_e908.hmm|GT2:33     167     NC_000913.3_355 399     3.6e-102        1       167     35      201     0.9940119760479041
GT2_e1093.hmm|GT2:36    128     NC_000913.3_3550        345     1.7e-66 1       128     10      137     0.9921875
GT9_e71.hmm|GT9:5354|2.4.99.-:11        224     NC_000913.3_3556        320     8.7e-113        1       222     78      299     0.9866071428571429
GT9_e82.hmm|GT9:222|2.4.1.56:10 212     NC_000913.3_3558        358     7.3e-125        1       212     107     317     0.9952830188679245
GT8_e183.hmm|GT8:1370|2.4.1.58:14       255     NC_000913.3_3561        339     3.4e-119        3       255     26      276     0.9882352941176471
GT9_e0.hmm|GT9:2054|2.4.99.-:11 240     NC_000913.3_3567        357     4.8e-121        1       239     79      317     0.9916666666666667
GT56_e0.hmm|GT56:4056|2.4.1.-:18|GT41:1 353     NC_000913.3_3720        360     3.3e-181        1       352     2       352     0.9943342776203966
AA2_e1.hmm|AA2:59       252     NC_000913.3_3863        727     5.1e-19 14      109     92      188     0.376984126984127
AA2_e1.hmm|AA2:59       252     NC_000913.3_3863        727     4.6e-18 16      249     461     720     0.9246031746031746
CBM34_e8.hmm|CBM34:3739|GH13_21:3729|3.2.1.20:14|3.2.1.1:3|GH13:3|CBM25:2|GH13_20:1     108     NC_000913.3_395 606     5.6e-46 1       107     7       113  0.9814814814814815
GH13_e88.hmm|GH13_21:161|CBM34:128|GH13_20:6|GH13:4|CBM25:2|3.2.1.1:1|3.2.1.133:1|3.2.1.20:1    315     NC_000913.3_395 606     2.4e-157        1       315  179      492     0.9968253968253968
GH13_e1.hmm|GH13_29:585|GH13:36|3.2.1.93:2|GH13_31:2    345     NC_000913.3_4154        552     5.9e-181        1       345     30      372     0.9971014492753624
CE9_e0.hmm|CE9:4926|3.5.1.25:23 370     NC_000913.3_659 383     3.6e-187        2       370     6       377     0.9945945945945946
GT2_e2088.hmm|GT2:253|2.4.1.-:1|GT8:1|GT0:1     280     NC_000913.3_999 442     7.7e-134        2       272     77      347     0.9642857142857143

total time: 133.76168608665466


***************************3. dbCAN_sub end***************************************************


No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
No substrate for it
Preparing overview table from hmmer, dbCAN_sub and diamond output...
overview table complete. Saved as output_EscheriaColiK12MG1655/overview.txt

**Comment by linnabrown** [comment]
Do you still have this issue?

**Comment by linnabrown** [comment]
Close this issue with no response.
