### ISSUE TITLE
Memory issues and restart procedure

### ISSUE THREAD

**Issue by aghozlane** [linnabrown/run_dbcan#134]
Hi,

I am trying to annotate several protein catalogues with >1M proteins but run_dbcan is killed every time by slurm due to memory consumption. I thought 50G of ram would be enough but I do not pass the hmmer step, but still not..

First, is there anyway to avoid to repeat the diamond step ? It takes a day..
Second, do you have implemented parameters to slice the data and avoid these memory issues ? 
Is there a nextflow or a snakemake somewhere to better utilize a cluster ?

Thank you,

**Comment by linnabrown** [comment]
I suggest that you can split your input proteins into different batches than run our code by submitting multiple jobs.

**Comment by aghozlane** [comment]
Hi, I wrote this https://gitlab.pasteur.fr/aghozlan/nf-dbcan to overcome this memory issue.
