### ISSUE TITLE
Updated PUL.faa file

### ISSUE THREAD

**Issue by jlubin24** [linnabrown/run_dbcan#135]
Hello 
Is there an updated PUL.faa file with all 673 PULs available to download?

thanks

**Comment by linnabrown** [comment]
Hi @yinlabniu could you answer this question? Thanks!

**Comment by azureycy** [comment]
> Hello Is there an updated PUL.faa file with all 673 PULs available to download?
> 
> thanks

Hi, we have uploaded the updated file PUL_12112023.faa with all 673 PULs available to download. Thank you.

**Comment by linnabrown** [comment]
@azureycy Hi Yuchen, thank you for answering this question. I would like to know whether the new version of PUL fasts file can replace the original one in our database downloading command ![image](https://github.com/linnabrown/run_dbcan/assets/9990190/2b732e67-e569-4fed-abfe-698e0795feaa)

**Comment by azureycy** [comment]
Hi Le, I can change the new file name to the original name if it’s needed.

Best regards,
Yuchen Yan
________________________________

**Comment by linnabrown** [comment]
@azureycy Hi Yuchen, you don't need to change it since I already updated readme.md. Thank you very much!

**Comment by linnabrown** [comment]
Hi @azureycy , please inform me when there is updated version of PUL.faa in the future, or you can PR in the database installation section in our readthedoc. Thank you very much!
