### ISSUE TITLE
Question: what does the magic number "5" means?

### ISSUE THREAD

**Issue by Hocnonsense** [linnabrown/run_dbcan#136]
https://github.com/linnabrown/run_dbcan/blob/288ccdaa82d1ede0cd9c70355b5e1284de0c90ae/dbcan_cli/run_dbcan.py#L91

Can this magic number `"--cpu", "5"` be modified by a command param? Thanks!

**Comment by linnabrown** [comment]
This is hmm_cpu. I will fix this bug in the next version

**Comment by linnabrown** [comment]
This problem has been resolved in 4.1.0. We will update this version in 24 hrs
