### ISSUE TITLE
The website may be wrong?

### ISSUE THREAD

**Issue by Lyang556** [linnabrown/run_dbcan#137]
Hi,

I tried to download the dbCAN-HMMdb-V11.txt from http://bcb.unl.edu/dbCAN2/download/Databases/V11/,  but there seems to be some problem with the URL and I can't open this page. I also tried https://bcb.unl.edu/dbCAN2/download/Databases/V11/ with the same result.

**Comment by linnabrown** [comment]
Hi Lyang,

This website works well here. Could you try it again?

**Comment by Lyang556** [comment]
Thank u, it works well now！
