### ISSUE TITLE
multiple genomes in one file or separate files?

### ISSUE THREAD

**Issue by Jigyasa3** [linnabrown/run_dbcan#139]
Hi,

I wanted to confirm if I am running `run_dbcan` on multiple genomes, can they be in a single fasta file with unique headers or do the genomes have to be in separate fasta files?

Looking forward to your reply.
Regards,
Jigyasa

**Comment by yinlabniu** [comment]
They can be in the same file as long as the seq ids are unique.
Yanbin
________________________________
From: Jigyasa Arora ***@***.***>
Sent: Thursday, December 7, 2023 10:34 PM
To: linnabrown/run_dbcan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [linnabrown/run_dbcan] multiple genomes in one file or separate files? (Issue #139)

Non-NU Email
________________________________

Hi,

I wanted to confirm if I am running run_dbcan on multiple genomes, can they be in a single fasta file with unique headers or do the genomes have to be in separate fasta files?

Looking forward to your reply.
Regards,
Jigyasa

**Comment by Jigyasa3** [comment]
thank you!
