### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by susheelbhanu** [linnabrown/run_dbcan#14]
Hi, 

I'm running the docker version with the following command:
```docker run --name B4 -v /Users/susheel.busi/Downloads:/Users/susheel.busi/Downloads -it haidyi/run_dbcan:latest python run_dbcan.py /Users/susheel.busi/Downloads/CAZyme_B4.faa protein --out_dir Downloads```

And I keep getting the below error for DIAMOND, Hmmer, and Hotpep:
```Building reference histograms... ***************************1. DIAMOND end***************************************************
Killed
Killed
Killed
Collecting Results
Traceback (most recent call last):
  File "parallel_group_many_proteins_many_patterns_noDNA.py", line 73, in <module>
    f = open(protein_dir_name+"/thread"+str(var1)+".txt", 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'CAZyme_B4/thread1.txt'
```

Your help is very much appreciated. 

Thank you,
Susheel

**Comment by susheelbhanu** [comment]
Additionally, the process has been stuck at this step for more than 45 minutes. Is this normal?
```
Assigning proteins to groups
Killed
Killed
Killed
Collecting Results
Traceback (most recent call last):
  File "parallel_group_many_proteins_many_patterns_noDNA.py", line 73, in <module>
    f = open(protein_dir_name+"/thread"+str(var1)+".txt", 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'CAZyme_B4/thread1.txt'

Screened
CAZyme_B4
for proteins of the types
CE, GH, AA, PL, GT, CBM
```

**Comment by linnabrown** [comment]
Thank you for your feedback. I am not sure what the problem exactly is. Can you share your input with me via e-mail so that I can test the code and try to fix this problem?

**Comment by susheelbhanu** [comment]
Hi Le Huang,

Thank you for the email. I have 2 datasets and the files are quite large. The one I was trying the run was “B4.faa”. I’ve uploaded them to Google Drive, so please let me know if you have trouble accessing them.

https://drive.google.com/open?id=12SDBqtYaEEJJXWPZjPwbK-auJNUH1Tak

Thank you very much,
Susheel

**Comment by susheelbhanu** [comment]
Hi, 

Here's the data: https://drive.google.com/open?id=12SDBqtYaEEJJXWPZjPwbK-auJNUH1Tak 

Please let me know if you have trouble accessing it. 

Thank you!

**Comment by linnabrown** [comment]
We tested in docker local server and it has result without any error traceback.

And I think your docker command is right.

May you need more powerful worskstation or server to run your data due to the size of your data is very big.

Thank you very much for your feed back.

**Comment by susheelbhanu** [comment]
Thank you.. Is there any way you could send me the results, so I could take a look?

**Comment by linnabrown** [comment]
[B4_result.zip](https://github.com/linnabrown/run_dbcan/files/3560129/B4_result.zip)

**Comment by linnabrown** [comment]
B12 is running in server, wait a miniute

**Comment by susheelbhanu** [comment]
Thank you very much for your help!

**Comment by linnabrown** [comment]
B12 done, there you go.
[B12_output.zip](https://github.com/linnabrown/run_dbcan/files/3561938/B12_output.zip)

**Comment by susheelbhanu** [comment]
Thank you very much!
