### ISSUE TITLE
Database update but code not update 

### ISSUE THREAD

**Issue by trx296554555** [linnabrown/run_dbcan#140]
Hi
First and foremost, I would like to express my sincere appreciation for your work. Your project has been immensely helpful to me.

I noticed, however, that while your README file recommends updating the database version to `fam-substrate-mapping-08012023.tsv` , the code itself still specifies an older version. This inconsistency has led to some confusion and potential compatibility issues.
https://github.com/linnabrown/run_dbcan/blob/9721d256a2b56416de66d42a7ffd9d58ed88c21e/dbcan_cli/run_dbcan.py#L289C39-L289C39

Thank you once again for your valuable contribution, and I look forward to your response regarding this matter.

Best regards,
Robin

**Comment by linnabrown** [comment]
Sorry about that. This is our hardcoding issue. We will resolve it asap in the updated package.

**Comment by linnabrown** [comment]
This issue has been resolved in version 4.1.0. We will put new version in 24 hours.
