### ISSUE TITLE
This repo violates the license for signalp

### ISSUE THREAD

**Issue by tesujimath** [linnabrown/run_dbcan#16]
The signalp README says this:
```
The SIGNALP package is a property of  Center for Biological Sequence Analysis.
It may be downloaded only by special agreement.  For academic users there is a
download site at:

	http://www.cbs.dtu.dk/cgi-bin/nph-sw_request?signalp

Other users are requested to contact software@cbs.dtu.dk.
```

The packaging here needs to simply declare a dependency on signalp.  To bundle the tarball as has been done violates this license.

Authorised users could do what we have done locally, and I recommend this.  Simply define your own internal, private, conda channel, add signalp to that channel using your own private download, and install from there using conda.  This is fine, it is simply redistribution which violates the license.

**Comment by yinlabniu** [comment]
Thanks for raising this issue. As suggested, we have removed signalp from our tarball and docker. Now if dbCAN users want to still run signalp within run_dbcan either locally or through docker, they are advised to acquire their own licensed signalp through CBS.
