### ISSUE TITLE
thread creation failed Fatal exception (source file esl_threads.c, line 139): thread creation failed

### ISSUE THREAD

**Issue by Panda-smile** [linnabrown/run_dbcan#163]
![image](https://github.com/linnabrown/run_dbcan/assets/143200215/ad710712-a1bb-4af5-80ca-d7436364a0ca)

I would like to ask how to solve this situation?
[slurm-117464.txt](https://github.com/linnabrown/run_dbcan/files/14321566/slurm-117464.txt)

#!/bin/bash
#SBATCH -J cazy
#SBATCH -p batch
#SBATCH -N 5
#SBATCH --ntasks-per-node=16
#SBATCH --mem=240GB

source ~/miniconda3/etc/profile.d/conda.sh
conda activate /public/home/zhanglj/miniconda3/envs/dbcan
cd /mnt/hpc/home/zhanglj/squeezemetatrans/shotguntrans/results/cazy

/public/home/zhanglj/miniconda3/envs/dbcan/bin/run_dbcan 03.shotguntrans.faa protein \
--dbcan_thread 16 --tf_cpu 16 --stp_cpu 16 -c 08.shotguntrans.gff --cgc_substrate \
--hmm_cpu 16 --out_dir ./ --dia_cpu 16 --db_dir /public/home/zhanglj/CazyDB/db \
--use_signalP=TRUE -sp /public/home/zhanglj/CazyDB/signalDB/signalp-4.1/signalp -g all

erro list：
thread creation failed
Fatal exception (source file esl_threads.c, line 139):
thread creation failed
Fatal exception (source file esl_threads.c, line 139):
thread creation failed
Fatal exception (source file esl_threads.c, line 139):
thread creation failed
Fatal exception (source file esl_threads.c, line 139):
Fatal exception (source file esl_threads.c, line 139):
thread creation failedthread creation failed

**Comment by ZhengJinfang1220** [comment]
Your log file shows the error happened when running HMMdbCAN-HMM database, we have fixed the bug in the updated version.

**Comment by Panda-smile** [comment]
Thanks a lot ， i will try it



发自我的iPhone


------------------ Original ------------------
From: ZhengJinfang1220 ***@***.***&gt;
Date: Thu,Mar 7,2024 9:45 AM
To: linnabrown/run_dbcan ***@***.***&gt;
Cc: jordan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [linnabrown/run_dbcan] thread creation failed Fatal exception(source file esl_threads.c, line 139): thread creation failed (Issue #163)





 
Your log file shows the error happened when running HMMdbCAN-HMM database, we have fixed the bug in the updated version.

**Comment by linnabrown** [comment]
@Panda-smile  Do you still have question? If not, please close with comment. Thanks
