### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by adityabandla** [linnabrown/run_dbcan#164]
Is the dbcan2 website currently down? Currently getting a timeout error

**Comment by yinlabniu** [comment]
Yes, it is. I announced on Twitter last week:

bcb.unl.edu/dbCAN2 is not accessible outside the university right now. We are working with ITS to address IT security issues. Please use our AWS mirror site for job submission for now: dbcan.unl.edu/dbcan/. Will announce here when the bcb server is back online.
________________________________
From: Aditya Bandla ***@***.***>
Sent: Sunday, February 18, 2024 5:14 PM
To: linnabrown/run_dbcan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [linnabrown/run_dbcan] Website down? (Issue #164)

Caution: Non-NU Email


Is the dbcan2 website currently down? Currently getting a timeout error

**Comment by adityabandla** [comment]
Thanks, much appreciated!

**Comment by HaidYi** [comment]
> Thanks, much appreciated!

The server is up now.
