### ISSUE TITLE
Visualizing dbcan gff output using Geneious

### ISSUE THREAD

**Issue by SevanEsaian** [linnabrown/run_dbcan#165]
Hello, 

I am working on identifying potential PULs in my metagenomes. I've run my dereplicated bins through prokka and dbCAN. I have uploaded the fasta file and prokka annotation to Geneious which overlap nicely. However, the dbCAN output file does not match the output structure of prokka; such that, I can't see the CAZyme annotation. Instead, it just says "CDS". 

My question is: do you have suggestion for where I can find a script that organizes the dbcan .gff output file; such that, I can see the corresponding CAZyme on Geneious alongside my .fasta file? 

Thank you.

**Comment by linnabrown** [comment]
Thank you for using our tool. You can use cgc_standard.out to do that

https://dbcan.readthedocs.io/en/latest/search.html?q=cgc_standard.out

**Comment by SevanEsaian** [comment]
Thank you for the suggestion. I will take a look at your link. If I have follow-up questions, I will contact you again in this thread.

**Comment by Xinpeng021001** [comment]
> Thank you for the suggestion. I will take a look at your link. If I have follow-up questions, I will contact you again in this thread.

Hi.

In the dbCAN3, we have the result of CAZyme and also, the cgc.gff, which is the result of CGCFinder. I just tested and if you could import the cgc.gff into Geneious, it would show you the visualization result (Attached file).

In our dbCAN-seq and dbCAN3 paper, we define that the CGC(CAZyme gene cluster) is the computational PULs, which include CAZyme, TC, TF, and STP (https://academic.oup.com/nar/article/51/W1/W115/7147496).

Hope this will help you. If needed we could try to generate the prokka-style output for CAZymes and CGCs in the future.

Please let me if you need anything else, or you could give us your example file to show.

Best,

![391709163103_ pic](https://github.com/linnabrown/run_dbcan/assets/84593788/c4e915c8-a93d-4b3a-9be4-0e0eb20ef2cf)

**Comment by linnabrown** [comment]
Do you still have question? @SevanEsaian
