### ISSUE TITLE
Are the latest CAZyme annotations using eukaryotic genomes sequences included in the run_bdcan databases ?

### ISSUE THREAD

**Issue by Balaveer** [linnabrown/run_dbcan#168]
Hii @linnabrown  and @yinlabniu, 
I have a small and quick question. On the http://www.cazy.org/Home.html webpage, the authors mentioned that "_in the end of 2023, we released on CAZy.org our expert annotation of the eukaryotic genomes sequenced by JGI after publication, including both MycoCosm and PhycoCosmprojects_!".
I would like to know whether these annotations were considered in the latest run_dbcan databases ? Thank you in advance!

**Comment by yinlabniu** [comment]
Not yet, but we will include them in the next yearly dbcan release (August 2024).

Yanbin

________________________________
From: Balaveer ***@***.***>
Sent: Saturday, March 2, 2024 9:15 AM
To: linnabrown/run_dbcan ***@***.***>
Cc: Yanbin Yin ***@***.***>; Mention ***@***.***>
Subject: [linnabrown/run_dbcan] Are the latest CAZyme annotations using eukaryotic genomes sequences included in the run_bdcan databases ? (Issue #168)

Caution: Non-NU Email


Hii @linnabrown<https://github.com/linnabrown> and @yinlabniu<https://github.com/yinlabniu>,
I have a small and quick question. On the http://www.cazy.org/Home.html webpage, the authors mentioned that "in the end of 2023, we released on CAZy.org our expert annotation of the eukaryotic genomes sequenced by JGI after publication, including both MycoCosm and PhycoCosmprojects!".
I would like to know whether these annotations were considered in the latest run_dbcan databases ? Thank you in advance!

**Comment by Balaveer** [comment]
Thank you for your quick answer!
