### ISSUE TITLE
Missing table headers in output file

### ISSUE THREAD

**Issue by HuangLoong** [linnabrown/run_dbcan#171]
![image](https://github.com/linnabrown/run_dbcan/assets/162462313/362ddead-53a0-4334-9b92-d59742a7b9bc)
![image](https://github.com/linnabrown/run_dbcan/assets/162462313/0161bd37-7859-45ba-a69d-8429d80be16e)

**Comment by linnabrown** [comment]
I don't think we provide hmmer.out and diamond.out. We only provide header in dbcan-sub.out
If you want to know the header, please refer to readthedoc document. I provided this link in the readme. Thank you.
