### ISSUE TITLE
meaning of repeated substrates

### ISSUE THREAD

**Issue by CamiAgustini** [linnabrown/run_dbcan#173]
Hi all, 

I am analyzing the data from the table that dbCAN gives me and I find that there are entries in which the repeated substrate appears, for example, some appear as a substrate "chitin" and others say "chitin, chitin". What is this about?

Another thing I don't understand is what the function of the number that follows the subfamily is, for example, for a GH18 I get "GH18_e428", what does the number after the e correspond to?

**Comment by Xinpeng021001** [comment]
Hi,
For the problem 1:
We use eCAMI (k-mer based) to create subfamilies for each CAZy family and then use CAZymes with EC number as a label to annotate the substrate (manually curation) for that subfamily. Then we build the HMM model for each subfamily wt/wo (some subfam could be assigned with substrates but some may not) substrates as the dbCAN-sub HMM.
![1831713809764_ pic_hd](https://github.com/linnabrown/run_dbcan/assets/84593788/e1bffaae-e020-4106-bd02-ca8649c09d55)
And sometimes CAZymes could be assigned with multiple subfamilies with different/same substrates (dbCAN-sub.out). That's the reason why she/he saw multiple substrates.

For the problem2:
"e_XX" means subfamily, such as GH18_e428.

![1871713810138_ pic_hd](https://github.com/linnabrown/run_dbcan/assets/84593788/1ddaf94c-e2b2-40d1-877b-7b264687475a)

Please review our dbCAN-seq update (https://doi.org/10.1093/nar/gkac1068) and dbCAN3 paper (https://doi.org/10.1093/nar/gkad328) if needed.

Hope this could help you.
Please let us know if you have any other questions.

**Comment by Xinpeng021001** [comment]
> I have another usage question pertaining to the substrates. Why are some of them missing? I would like to know the substrates of all of the cazymes. I understand that this is a matter of manual curation, but is there a place where I can find the missing ones?
> 
> <img alt="Screenshot 2024-04-23 at 10 25 59" width="366" src="https://private-user-images.githubusercontent.com/5913696/324754794-0c730c4b-01b8-48cb-b247-e3f96308d807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzkwNjMsIm5iZiI6MTcxMzg3ODc2MywicGF0aCI6Ii81OTEzNjk2LzMyNDc1NDc5NC0wYzczMGM0Yi0wMWI4LTQ4Y2ItYjI0Ny1lM2Y5NjMwOGQ4MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTMyNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIyYWNmOWJkODM1M2VmMWY3NDJlMjU1MGI4MWNkYmY0NDgzOWYyYTM5NjA5M2ViYzJjOTY0ZGU3OGU5ZmY2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pN6ambNnN7Pls1Bm0CUk_MKEf9XL4embIr4JNpZOLWU">

Hi,
In CAZy database, there are two types of CAZymes: with EC number and without EC number (most). We use the EC number as a label to assign a substrate for our subfamily because those could be curated with known substrates from literature or databases like BRENDA. However, as we mentioned, there are a great many CAZymes without EC number and some subfamilies can only be assigned with those CAZymes. That's the reason why you can't find substrates for those subfamilies.

If you want to find those substrates, I would suggest you do some literature review or use our supplements in dbCAN3 to find a substrate/substrates at the CAZyme family level, not the subfamily level.
