### ISSUE TITLE
fam-substrate-mapping.tsv missing

### ISSUE THREAD

**Issue by cmkobel** [linnabrown/run_dbcan#174]
Using latest biconda release (4.1.4)
Just downloaded a fresh database.

When running, it seems like "fam-substrate-mapping.tsv" is not present in the database dir. I copied "fam-substrate-mapping-08252022.tsv" and everything looks to be working fine. 

Maybe this file should be renamed in the database?

Best, Carl

**Comment by cluckit** [comment]
I also get this error when running dbcan via docker.  
FileNotFoundError: [Errno 2] No such file or directory: 'db/fam-substrate-mapping.tsv'

I also tried to install with conda, but thats even worse:
db/ ERROR: The database directory does not exist

where do I find the new file with the date, and where do I put it?

**Comment by Xinpeng021001** [comment]
@cluckit @cmkobel Hi all, please check the db folder and see if there's any file called fam-substrate-xxxx.tsv, we updated the substrate file before (now it should be [fam-substrate-mapping-08012023.tsv](https://bcb.unl.edu/dbCAN2/download/Databases/fam-substrate-mapping-08012023.tsv), also we're updating this table recently so we will upload another version in few days.
