### ISSUE TITLE
cgc predict fail 

### ISSUE THREAD

**Issue by Panda-smile** [linnabrown/run_dbcan#177]
###  @Report

#!/bin/bash
#SBATCH -J NAMD
#SBATCH -p batch
#SBATCH -N 1
#SBATCH --ntasks-per-node=32

source ~/miniconda3/etc/profile.d/conda.sh
conda activate /public/home/lj/miniconda3/envs/dbcan

run_dbcan /public/home/lj/CazyDB/temp/qc/Saccharomycopsisproteins.faa protein --dbcan_thread 32 --tf_cpu 32 --stp_cpu 32 -c /public/home/lj/CazyDB/temp/qc/Saccharomycopsis.gff --cgc_substrate --hmm_cpu 32 --out_dir SF.PUL --dia_cpu 32 --db_dir /public/home/lj/CazyDB/db

Hello Professor,

I would like to seek your guidance on an issue. After running the aforementioned code, I did not obtain the expected predictions related to cgc predict results (such as PUL and synpdf). I am wondering if this issue might be related to the input file I used. I have attached my gff format file, which is the result of an output from the funnannotate software. Could you please advise me on how to modify or process my GFF file to meet the requirements of dbCAN?I am looking forward to your reply.

Best regards
Panda-smile
![image](https://github.com/linnabrown/run_dbcan/assets/143200215/1b4e057b-a37f-48f8-99d8-2828e1088c22)

<img width="963" alt="image" src="https://github.com/linnabrown/run_dbcan/assets/143200215/cfb56538-5fac-4e80-897a-b61ad753e117">
1）gff文件（已做后缀修改，替换为txt）：[Saccharomycopsis.txt](https://github.com/linnabrown/run_dbcan/files/15397161/Saccharomycopsis.txt)

2）蛋白序列为：[Saccharomycopsisproteinsfaa.txt](https://github.com/linnabrown/run_dbcan/files/15397104/Saccharomycopsisproteinsfaa.txt)

**Comment by Xinpeng021001** [comment]
Hi, you're using fungi genomes which can't be supported with CGC-prediction right now. We're developing a special version for the fungi genomes. For now, only prok genomes could do the CGC prediction.

**Comment by Panda-smile** [comment]
Hello Professor,

I would like to ask how I can incorporate my "position.xls" file as a basis for CGC prediction?





#!/bin/bash
#SBATCH -J cazy
#SBATCH -p batch
#SBATCH -N 1
#SBATCH --ntasks-per-node=32
#SBATCH #--cpus-per-task=32


/public/home/z/miniconda/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py run_dbcan /public/home/z/CazyDB/Data/testdata/EscheriaColiK12MG1655.faa protein -c /public/home/z/CazyDB/Data/testdata/EscheriaColiK12MG1655.gff --dia_cpu 32 --hmm_cpu 32 --tf_cpu 32 --stp_cpu 32 --out_pre test --out_dir test0927 --use_signalP=TRUE -sp /public/home/z/CazyDB/signalDB/signalp-4.1/signalp -g all --db_dir /public/home/z/CazyDB/db --cgc_substrate







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linnabrown/run_dbcan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 上午9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linnabrown/run_dbcan] cgc predict fail  (Issue #177)





 
Hi, you're using fungi genomes which can't be supported with CGC-prediction right now. We're developing a special version for the fungi genomes. For now, only prok genomes could do the CGC prediction.

**Comment by Xinpeng021001** [comment]
> Hello Professor, I would like to ask how I can incorporate my "position.xls" file as a basis for CGC prediction? #!/bin/bash #SBATCH -J cazy #SBATCH -p batch #SBATCH -N 1 #SBATCH --ntasks-per-node=32 #SBATCH #--cpus-per-task=32 /public/home/z/miniconda/envs/run_dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py run_dbcan /public/home/z/CazyDB/Data/testdata/EscheriaColiK12MG1655.faa protein -c /public/home/z/CazyDB/Data/testdata/EscheriaColiK12MG1655.gff --dia_cpu 32 --hmm_cpu 32 --tf_cpu 32 --stp_cpu 32 --out_pre test --out_dir test0927 --use_signalP=TRUE -sp /public/home/z/CazyDB/signalDB/signalp-4.1/signalp -g all --db_dir /public/home/z/CazyDB/db --cgc_substrate
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "linnabrown/run_dbcan" ***@***.***&gt;; 发送时间:&nbsp;2024年9月20日(星期五) 上午9:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [linnabrown/run_dbcan] cgc predict fail (Issue #177) Hi, you're using fungi genomes which can't be supported with CGC-prediction right now. We're developing a special version for the fungi genomes. For now, only prok genomes could do the CGC prediction. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi, sorry but we can not support the CGC prediction for the fungi genome right now. Besides, I didn't find your xls files.
