### ISSUE TITLE
Newest version of dbcan not available on PyPI

### ISSUE THREAD

**Issue by nuzhathoque** [linnabrown/run_dbcan#178]
### Description of feature

Hi! 
I installed dbcan using the command `pip3 install dbcan`, but it seems like this installs the previous version (v3.0.6) of dbcan. I've tried to use conda to install packages, but it always returns that I am missing channels and thus cannot install using conda. Would it be possible to make the latest version of this python package available on PyPI?
Thank you so much!

**Comment by caelanjmiller** [comment]
Hi @nuzhathoque, you can install the latest version via `pip` by navigating to the releases page and grabbing the link for the source release archive (under Assets) ([latest version 4.1.4](https://github.com/linnabrown/run_dbcan/releases/download/4.1.4/dbcan-4.1.4.tar.gz)) and download to a directory of your choice via `curl` or `wget`. Once downloaded, you can use `pip install dbcan-4.1.4.tar.gz` to install the package directly

**Comment by nuzhathoque** [comment]
Thanks!

**Comment by nuzhathoque** [comment]
Thank you! That makes sense
