### ISSUE TITLE
Improve packaging and distribution

### ISSUE THREAD

**Issue by tesujimath** [linnabrown/run_dbcan#18]
This software is currently unpackaged.  This is what is making it difficult for users.  The solution is not more detailed manual instructions, but to package it, so that users may easily install it from e.g. pip or conda.

In order to do this, there are some improvements that need to be made, for example, separating the code from the data, not writing output files into the directory where the scripts live, etc.  All of this may be solved by packaging it.

Since the dependencies (diamond, hmmer, prodigal, graggenescan) are available via conda on the bioconda channel, that only leaves signalp to worry about, which greatly simplifies the installation.  So I am recommending a conda packaging for dbcan, including the Hotpep scripts.

I am happy to contribute what is required.  It will involve some cleaning up of the software.  For this repo, this means at least a setup.py file.  And then a recipe in bioconda.

Will you consider such a pull request?

**Comment by linnabrown** [comment]
Thank you for your suggestion. Could you provide us with some manuals of creating bioconda package?

**Comment by tesujimath** [comment]
I intend to do this for you, and contribute a pull request.

In the meantime, the documentation is here: https://bioconda.github.io/contributor/index.html
