### ISSUE TITLE
dbcan 3 start from raw data,I got some problems with step 13 dbcan_utils to calculate the abundance of CAZyme families, subfamilies, CGCs, and substrates

### ISSUE THREAD

**Issue by powerby66** [linnabrown/run_dbcan#180]
### Report

dbcan_utils fam_abund -bt /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_abund/EscheriaColiK12MG1655.depth.txt -i /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_fna.dbCAN -a TPM
dbcan_utils fam_substrate_abund -bt /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_abund/EscheriaColiK12MG1655.depth.txt -i /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_fna.dbCAN -a TPM
dbcan_utils CGC_abund -bt /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_abund/EscheriaColiK12MG1655.depth.txt -i /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_fna.dbCAN -a TPM
dbcan_utils CGC_substrate_abund -bt /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_abund/EscheriaColiK12MG1655.depth.txt -i /data2/jpc/project/project/db_test/output/EscheriaColiK12MG1655_fna.dbCAN -a TPM 
This step shows 'dbcan_utils command not found', so I directly imported utils.py, 
![image](https://github.com/linnabrown/run_dbcan/assets/173457621/ce0fc2ec-f117-4054-8f02-474ebb0bdbc5)
but there were no results output or error message. What is the correct way to proceed? Thank you!

**Comment by Xinpeng021001** [comment]
Hi, you don't need to use "python xxxxx.py" to do that, could you please update the dbCAN version at branch 4.x of your conda env? I guess you used an old version and that might be the reason.
