### ISSUE TITLE
Inquiry Regarding KeyError 'TC' in dbcan_utils CGC_abund Function

### ISSUE THREAD

**Issue by jiangys30** [linnabrown/run_dbcan#181]
### Report

Hello, I am a new user of dbcan. While running the following command:
`dbcan_utils CGC_abund -bt Bv_WXH_abund/Bv_WXH.depth.txt -i dbcan_result -a TPM
`
I encountered the following error:
```
Traceback (most recent call last):
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/bin/dbcan_utils", line 10, in <module>
    sys.exit(main())
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 619, in main
    PUL_abundance(args)
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 493, in PUL_abundance
    PUL_abund.output_cgc_abund()
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 462, in output_cgc_abund
    cgc_standard_records.append(self.cgcid2cgc_standard[cgcid])
KeyError: 'TC'
```
This error indicates that the **self.cgcid2cgc_standard dictionary does not contain the key 'TC'** when executing the output_cgc_abund function.

Additionally, while running:
`dbcan_utils CGC_substrate_abund -bt Bv_WXH_abund/Bv_WXH.depth.txt -i dbcan_result -a TPM
`
I encountered a similar error:
```
Traceback (most recent call last):
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/bin/dbcan_utils", line 10, in <module>
    sys.exit(main())
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 622, in main
    PUL_Substrate_abundance(args)
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 500, in PUL_Substrate_abundance
    PUL_abund.Cal_PUL_Substrate_Abundance()
  File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 371, in Cal_PUL_Substrate_Abundance
    cgc_abunds = self.cgcid2seqabund[cgcid]  ### list constis of sequence abundance
KeyError: 'NODE_4_length_250273_cov_247.905346|CGC1'
```
Can anyone please guide me on how to resolve these issues? Attached is the screenshot of my input file, the **cgc_standard.out** file. I noticed in a previous issue tracker that the input file for dbcan_utils CGC_abund is cgc_standard.out. However, I am unsure what the input should be for dbcan_utils CGC_substrate_abund.
![image](https://github.com/linnabrown/run_dbcan/assets/118042246/2bed1819-92f1-47dc-9cf7-29f3606c09d3)

Here is some additional information that might be helpful: I followed the protocol outlined in _"Run from Raw Reads: Automated CAZyme and Glycan Substrate Annotation in Microbiomes: A Step-by-Step Protocol"_. However, I did not use all the software recommended in the tutorial. Instead, I utilized alternative software for some steps because I had pre-developed parts of the workflow. My workflow diagram is as follows:
![image](https://github.com/linnabrown/run_dbcan/assets/118042246/f89640df-ca64-4328-b326-0a63c0fd4035)

**Comment by ZhengJinfang1220** [comment]
> ### Report
> Hello, I am a new user of dbcan. While running the following command: `dbcan_utils CGC_abund -bt Bv_WXH_abund/Bv_WXH.depth.txt -i dbcan_result -a TPM ` I encountered the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/bin/dbcan_utils", line 10, in <module>
>     sys.exit(main())
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 619, in main
>     PUL_abundance(args)
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 493, in PUL_abundance
>     PUL_abund.output_cgc_abund()
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 462, in output_cgc_abund
>     cgc_standard_records.append(self.cgcid2cgc_standard[cgcid])
> KeyError: 'TC'
> ```
> 
> This error indicates that the **self.cgcid2cgc_standard dictionary does not contain the key 'TC'** when executing the output_cgc_abund function.
> 
> Additionally, while running: `dbcan_utils CGC_substrate_abund -bt Bv_WXH_abund/Bv_WXH.depth.txt -i dbcan_result -a TPM ` I encountered a similar error:
> 
> ```
> Traceback (most recent call last):
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/bin/dbcan_utils", line 10, in <module>
>     sys.exit(main())
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 622, in main
>     PUL_Substrate_abundance(args)
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 500, in PUL_Substrate_abundance
>     PUL_abund.Cal_PUL_Substrate_Abundance()
>   File "/lustre1/g/aos_shihuang/tools/anaconda3/envs/dbcan/lib/python3.8/site-packages/dbcan/utils/utils.py", line 371, in Cal_PUL_Substrate_Abundance
>     cgc_abunds = self.cgcid2seqabund[cgcid]  ### list constis of sequence abundance
> KeyError: 'NODE_4_length_250273_cov_247.905346|CGC1'
> ```
> 
> Can anyone please guide me on how to resolve these issues? Attached is the screenshot of my input file, the **cgc_standard.out** file. I noticed in a previous issue tracker that the input file for dbcan_utils CGC_abund is cgc_standard.out. However, I am unsure what the input should be for dbcan_utils CGC_substrate_abund. ![image](https://private-user-images.githubusercontent.com/118042246/347254120-2bed1819-92f1-47dc-9cf7-29f3606c09d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjE2NzksIm5iZiI6MTcyMDY2MTM3OSwicGF0aCI6Ii8xMTgwNDIyNDYvMzQ3MjU0MTIwLTJiZWQxODE5LTkyZjEtNDdkYy05Y2Y3LTI5ZjM2MDZjMDlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMTI5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWFmZDI3ZGE5MDgyMDU0NWIyNTY3MDlhODkwMjZjZDE0ZWM4ZjJhZThhZmYxM2YzNzM2ZTZmNDlhMDQyNTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wOGwLYFwiWNkyhTaMW5Z1dgopehJAkgoHs1895LdpZU)
> 
> Here is some additional information that might be helpful: I followed the protocol outlined in _"Run from Raw Reads: Automated CAZyme and Glycan Substrate Annotation in Microbiomes: A Step-by-Step Protocol"_. However, I did not use all the software recommended in the tutorial. Instead, I utilized alternative software for some steps because I had pre-developed parts of the workflow. My workflow diagram is as follows: ![image](https://private-user-images.githubusercontent.com/118042246/347254313-f89640df-ca64-4328-b326-0a63c0fd4035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjE2NzksIm5iZiI6MTcyMDY2MTM3OSwicGF0aCI6Ii8xMTgwNDIyNDYvMzQ3MjU0MzEzLWY4OTY0MGRmLWNhNjQtNDMyOC1iMzI2LTBhNjNjMGZkNDAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMTI5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzljNGE2YzY4ZmM0YjNkZTY5ODlhNGNjN2NmOWViZjJkZDQ4NWQ1NzIxYTc0OTVmNDI2ZTZkYTM2NTE3MjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KLmwKjNTMV7-IBiXe0gIPONZjoo1hd8PW3WObckBNc)
> 
> ### Version information
> _No response_

Hi, the error prompt is wired. I did not encounter this bug before. Could you share the data with me (zhengjinfang1220@gmail.com)?
