### ISSUE TITLE
dbCAN_utils output problem

### ISSUE THREAD

**Issue by Wqqqr224** [linnabrown/run_dbcan#186]
### Report

I am trying to run dbCAN_utils for multiple MAGs using metadata_fil.txt, but it the output I am getting is single and it has been overwritten. I tried --output ${line}.out (also --outpubut its not working its keeps giving single outputs (overwritten).
for example
 dbcan_utils fam_abund -bt ${line}.depth.txt -i ${line}.dbCAN -a TPM --output ${line}_fam_abund.out
 but the outputs I am getting are without unique identities and that's why it's overwritten.
 How do you get outputs with a unique identifier so it's not overwritten?

**Comment by Xinpeng021001** [comment]
Hi, I suggest you rename the output file by command lines like using mv or rename to do that. We didn't provide a parameter to change the output file name.
