### ISSUE TITLE
How to interpret entries where multiple Subfam Compositions and Subfam ECs appear in the same line?

### ISSUE THREAD

**Issue by xubiy** [linnabrown/run_dbcan#189]
### Description of feature

I am trying to confirm the implication of predicted enzyme functions in lignocellulose degradation. 
While organizing the 'dbcan-sub.hmm.out' file, I encountered some confusion regarding the dbCAN subfam annotations. 
As seen in the highlighted sections of the screenshot, each GH3_e0 annotation result corresponds to **multiple** **Subfam Compositions** and **Subfam ECs**, separated by '|'. In such cases, which Subfam Composition should I consider? Among the multiple EC numbers annotated, which one is related to GH3_e0 and which ones are related to CBM or GH67?
Based on my current limited understanding, I believe that among the many Subfam Compositions, GH3:1894 is the most ideal annotation for GH3_e0. And among the many Subfam ECs, I think these EC numbers represent all possible functions of GH3, not CBM nor GH67. Is my understanding accurate, could you help me interpret this?
<img width="803" alt="7aacdacdce33e760f8d3253e2170a21" src="https://github.com/user-attachments/assets/6209c7f3-1189-462c-a5a2-cb16dccc4c58">

**Comment by yinlabniu** [comment]
You are correct. The short answer is to the substrate shown in the front. For your highlighted rows, it will be xylan. The second column indicates the CAZy protein members in GH3_e0. 

More detailed info for this dbCAN subfam is at https://bcb.unl.edu/dbCAN_sub/dbsub.php?contig=GH3_e0. You will see this subfam has 1894 proteins annotated in the CAZy website. A small number of proteins of these 1894 also contain other domains (GH67, CBM67, CBM6, CBM32). This subfam also contain 134 proteins with EC numbers (again from CAZy website). The most abundant EC is 3.2.1.37 with 92 proteins. The xyan substrate in the third column is from this EC (according to https://bcb.unl.edu/dbCAN2/download/dbsub_data/Substrate_05-03-2022.txt).

**Comment by xubiy** [comment]
> You are correct. The short answer is to choose the substrate shown in the front. For your highlighted rows, it will be xylan. The second column indicates the CAZy protein members in GH3_e0.
> 
> More detailed info for this dbCAN subfam is at https://bcb.unl.edu/dbCAN_sub/dbsub.php?contig=GH3_e0. You will see this subfam has 1894 proteins annotated in the CAZy website. A small number of proteins of these 1894 also contain other domains (GH67, CBM67, CBM6, CBM32). This subfam also contain 134 proteins with EC numbers (again from CAZy website). The most abundant EC is 3.2.1.37 with 92 proteins. The xyan substrate in the third column is from this EC (according to https://bcb.unl.edu/dbCAN2/download/dbsub_data/Substrate_05-03-2022.txt).

Thank you for your answer!
