### ISSUE TITLE
Inquiry on error

### ISSUE THREAD

**Issue by songmj86** [linnabrown/run_dbcan#191]
### Report

Hi. I installed the dbcan via conda and encounted the issue "File not found: [Errno 2] No such file or directory: '/$Out/hmmer.out'".  Do you have any idea how to resolve this issue?  Thanks

### Install
conda create -y -n dbcan python=3.8 ;
conda activate dbcan ; 
conda install -y -n dbcan dbcan

#### DB construction 
conda activate dbcan ; dbcan_build -h ; 
Out="Path" ; mkdir -p $Out ;  
dbcan_build --db-dir $Out --clean

### Run (Input is protein faa file)
conda activate dbcan ;
DB="Path1" ;
In="Path2" ; 
Out="Path3" ;
run_dbcan --db_dir $DB --dia_cpu 100 --hmm_cpu 100 --dbcan_thread 100 --tf_cpu 100 --stp_cpu 100 --out_dir $Out $In protein
conda deactivate ; 

### Result

***************************1. DIAMOND start*************************************************

***************************1. DIAMOND end***************************************************

***************************2. HMMER start*************************************************

***************************2. HMMER end***************************************************

***************************3. dbCAN_sub start***************************************************

total time: 202.39654803276062

***************************3. dbCAN_sub end***************************************************

File not found: [Errno 2] No such file or directory: '/$Out/hmmer.out'
Preparing overview table from hmmer, dbCAN_sub and diamond output...
Overview table complete. Saved as /$Out/overview.txt

### Attachment is the computed results 
[Result.zip](https://github.com/user-attachments/files/17928930/Result.zip)

**Comment by Xinpeng021001** [comment]
Hi, this means from the HMMER you don't get any result, which means your input may not contain CAZymes.
