### ISSUE TITLE
metadata file linking to taxonomy for the latest release. 

### ISSUE THREAD

**Issue by raw937** [linnabrown/run_dbcan#2]
Hello,

The latest release for dbcan2 is the CAZyDB.07312018.fa
on http://bcb.unl.edu/dbCAN2/download/Databases/
grep ">" CAZyDB.07312018.fa | more
>AWH92887.1|GH29
>AWI06118.1|GT2
>AWH92887.1|GH29

These 'AWH92887.1' are genbank IDs. 
It would be great to have a metadata file linking these to taxonomy
For examples:
AWH92887.1 Bacteria; Actinobacteria; Corynebacteriales; Dietziaceae; Dietzia; Dietzia lutea

If you could send me this on put on the FTP site that would be great.

Many thanks
Rick

**Comment by linnabrown** [comment]
sounds great :+1:

**Comment by raw937** [comment]
Do you have the list for the genbank IDs? It would be very helpful.

**Comment by linnabrown** [comment]
you can download it from NCBI taxonomy and then filter it.

**Comment by linnabrown** [comment]
Sorry, I do not have enough time to do so. But I think you could try to write a script as following:
1. Download page such as :https://www.ncbi.nlm.nih.gov/ipg/?term=AWH92887.1
2. Extract gcf ID
3. Search taxid related to gcf id in a table download from taxonomy
4. Then, you know, search taxid id in another big table download from NCBI
4.

**Comment by linnabrown** [comment]
> Do you have the list for the genbank IDs? It would be very helpful.

I am busy with my dissertation until tomorrow. Please give me some time to do above.

**Comment by raw937** [comment]
Yup. I pulled them from the headers.

I was playing with this one:
https://github.com/dib-lab/2018-ncbi-lineages

But, I am at a conference currently.

The thing above should do it.

**Comment by linnabrown** [comment]
```
1. Make sure docker is installed on your computer successfully.
2. docker pull haidyi/run_dbcan:latest
3. docker run --name <preferred_name> -v <host-path>:<container-path> -it haidyi/run_dbcan:latest python run_dbcan.py <input_file> [params] --out_dir <output_dir>
```
