### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train_many_organisms_many_families.py' error

### ISSUE THREAD

**Issue by songweizhi** [linnabrown/run_dbcan#20]
Dear linnabrown,
I got an error saying "FileNotFoundError: [Errno 2] No such file or directory: 'train_many_organisms_many_families.py': 'train_many_organisms_many_families.py'". Do you have any idea why this happened? I have the Hotpep folder and the run_dbcan.py in the same directory (simply unzipped the run_dbcan master repository).

Your kind help will be highly appreciated!
Thanks,
Weizhi

**Comment by linnabrown** [comment]
Please wait for these days of bioconda version release. Thank you very much!

**Comment by linnabrown** [comment]
We create a python package. Use these following command to install.

You can install Anaconda or Miniconda first, and then use the following commands to install our program one time. I strongly recommend you to use virtual environment to keey away from messing your system up. Just

#create virtual environment
mkdir -p ~/virtualenvs
python3 -m venv ~/virtualenvs/run_dbcan
source ~/virtualenvs/run_dbcan/bin/activate
pip install run-dbcan==2.0.0
# Doanload dependencies from bioconda
conda install -c bioconda diamond hmmer=3.1b2 prodigal fraggenescan

# Download and make the database for run_dbcan
test -d db || mkdir db
cd db \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fa && diamond makedb --in CAZyDB.07312018.fa -d CAZy \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V7.txt && mv dbCAN-HMMdb-V7.txt dbCAN.txt && hmmpress dbCAN.txt \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tcdb.fa && diamond makedb --in tcdb.fa -d tcdb \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-1.hmm && hmmpress tf-1.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-2.hmm && hmmpress tf-2.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/stp.hmm && hmmpress stp.hmm \
    && cd ../ && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.fna \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.faa \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.gff
# try this command to see whether this sample can work now
run_dbcan.py EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655
