### ISSUE TITLE
db/ ERROR: The database directory does not exist

### ISSUE THREAD

**Issue by lifadeng** [linnabrown/run_dbcan#21]
I download the database and make them in a flowder, when I type the test commond, something wrong with it, can't locate the db file, how can I deal with it ?? Thanks 
我从其他服务器下载了数据库文件，然后在一个文件夹下解压了数据库，但是当我 跑测试命令的时候显示无法找到数据库，请问我该如何指定数据库文件夹，谢谢

**Comment by linnabrown** [comment]
???
put db/ in the same root of run_dbcan.py
