### ISSUE TITLE
TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by jasmineliang** [linnabrown/run_dbcan#22]
Hello!

When I ran the run_dbcan.py, I came into the problem below:

Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "run_dbcan.py", line 626, in <module>
    hits["signalP" : "N"]
TypeError: unhashable type: 'slice'

How can I solve this? Thank you for your reply!

**Comment by linnabrown** [comment]
Thanks for your feedback for bugs on Github source code.

Actually, I have revised locally and put up python package.

Please refer to readme for more information.

If you would like to, I also upload a conda version which includes all of the dependencies except database. 

Here is an conda install instance

```
conda install run_dbcan -c keaidelele -c bioconda
```

And then download database use this command 

```
test -d db || mkdir db
cd db \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fa && diamond makedb --in CAZyDB.07312018.fa -d CAZy \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V8.txt && mv dbCAN-HMMdb-V8.txt dbCAN.txt && hmmpress dbCAN.txt \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tcdb.fa && diamond makedb --in tcdb.fa -d tcdb \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-1.hmm && hmmpress tf-1.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-2.hmm && hmmpress tf-2.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/stp.hmm && hmmpress stp.hmm \
    && cd ../ && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.fna \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.faa \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.gff
```

We actually did not deprecate signalP. But you need to download it by yourself.
What's more, our python package, conda package and docker image would not include this because of its license.

**Comment by jasmineliang** [comment]
Thanks very much for your prompt reply!

I downloaded signalP and installed it following your instructions.  It was ok to run signalp alone, and there was a signalp.out file in the output dictionary when I ran  run_dbcan.py. It seems that signalp worked well. However, the overview.txt only had the headlines without any output. The log file showed as below:

Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
File "run_dbcan.py", line 626, in 
hits["signalP" : "N"]
TypeError: unhashable type: 'slice'

Is there something wrong with the script that produce the overview.txt?

**Comment by linnabrown** [comment]
You need to use the new script in https://github.com/linnabrown/run_dbcan/blob/master/run_dbcan.py to replace the previous one and add `--use_signalP True`.  

Make sure signalp script  is added on `/usr/bin`

Again, I recommend you to use python package as I mentioned just now.

Python Package Usage
-----
1. Please install [Anoconda](https://www.anaconda.com) first.

2. Install this package with pip.
```
pip install run-dbcan --user
```
3. Install dependencies with conda. 
```
conda install -c bioconda diamond hmmer=3.1b2 prodigal fraggenescan
```
4. Database Installation.
```
test -d db || mkdir db
cd db \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fa && diamond makedb --in CAZyDB.07312018.fa -d CAZy \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V8.txt && mv dbCAN-HMMdb-V8.txt dbCAN.txt && hmmpress dbCAN.txt \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tcdb.fa && diamond makedb --in tcdb.fa -d tcdb \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-1.hmm && hmmpress tf-1.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/tf-2.hmm && hmmpress tf-2.hmm \
    && wget http://bcb.unl.edu/dbCAN2/download/Databases/stp.hmm && hmmpress stp.hmm \
    && cd ../ && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.fna \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.faa \
    && wget http://bcb.unl.edu/dbCAN2/download/Samples/EscheriaColiK12MG1655.gff
```
5. (Optional) SignalP Installation.
Our program include Signalp Petitide prediction with SignalP. Make sure to set `use_signalP=True` and *have to* obtain your own academic license of SignalP and download it from [here](http://www.cbs.dtu.dk/cgi-bin/sw_request?signalp+4.1), and then move tarball (Signalp-4.1.tar.gz) into `run_dbcan/tools/` by yourself. Following statement is singalP-4.0 installation instruction.
```
mkdir -p run_dbcan/tools && run_dbcan/tools/
tar xzf Signalp-4.1.tar.gz && cd Signalp-4.1
```
Edit the paragraph labeled  "GENERAL SETTINGS, CUSTOMIZE ..." in the top of
   the file 'signalp'. The following twovmandatory variables need to be set:
   
   	SIGNALP		full path to the signalp-4.1 directory on your system
	outputDir	where to store temporary files (writable to all users)

   In addition,  for practical reasons,  it is possible to limit the number of
   input sequences allowed per run (MAX_ALLOWED_ENTRIES). For example:
```
###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the signalp-4.1 directory on your system (mandatory)
BEGIN {
    $ENV{SIGNALP} = '/home/abc/Desktop/run_dbcan/tools/signalp-4.1';
}

# determine where to store temporary files (must be writable to all users)
my $outputDir = "/home/abc/Desktop/run_dbcan/tools/signalp-4.1/output";

# max number of sequences per run (any number can be handled)
my $MAX_ALLOWED_ENTRIES=100000;
```

And then, use this command:

```
sudo cp signalp /usr/bin/signalp
sudo chmod 755 /usr/bin/signalp
```
6. Check Program.
```
run_dbcan.py EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655
```

**Comment by linnabrown** [comment]
I have fix the bug now.
please refer to this, thank you!
revise `hits["signalP" : "N"]` to `hits = ["signalP" : "N"]`

**Comment by jasmineliang** [comment]
I think it should be hits = {"signalP" : "N"}?

**Comment by linnabrown** [comment]
Yes exactly. Thank you so much!

**Comment by jasmineliang** [comment]
The previous bug is fixed. However, a new one came up as below:

Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "/home/linyy/.local/bin/run_dbcan.py", line 632, in <module>
    hits["tools"]+=1
KeyError: 'tools'

How to fix this?

**Comment by linnabrown** [comment]
hits["signalP"] = "N"

**Comment by adityabandla** [comment]
Im still running into this issue. I followed the instructions on README

**Comment by linnabrown** [comment]
I did not change the package of this issue.
I will do this before this end of the weekend. Thank you for your patience.

**Comment by adityabandla** [comment]
Was this fixed?

**Comment by linnabrown** [comment]
Yes it has been fixed. please refer to the updated readme.
You can just do this following command
```
pip install run-dbcan==2.0.1 --user
```
