### ISSUE TITLE
error in preparing overview table

### ISSUE THREAD

**Issue by lis4matilda** [linnabrown/run_dbcan#24]
Hi
I have used the conda installation and installed signalP separately. I run with the option --use_signalP=True. Everything works fine up to the summarising of the results. This happens both for the example data and the test run with my data. Results files from DIAMOND, HMMER and hotPep is created. Hope you can help. Lisa

***************************1. DIAMOND end***************************************************
***************************2. HMMER end***************************************************
***************************3. hotPep end***************************************************
Waiting on signalP
SignalP complete
Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "/home/lisao/.local/bin/run_dbcan.py", line 626, in <module>
    hits["signalP" : "N"]
TypeError: unhashable type: 'slice'

**Comment by linnabrown** [comment]
This problem is solved in our GitHub repository. You can download repository from github and replace /home/lisao/.local/bin/run_dbcan.py with run_dbcan.py.

I will revise the pip package (pip install run_dbcan) several days later.
Thanks for using.

**Comment by linnabrown** [comment]
This problem has been solved in the new package.
Please use this command

```
pip install run-dbcan==2.0.1 --user
```
