### ISSUE TITLE
How to get the relative abundance table? 

### ISSUE THREAD

**Issue by HNUmcc** [linnabrown/run_dbcan#26]
Hi
I don't know how to get the relative abundance results based on run_dbcan2 (diamond outputs). So, what should i do the next step?
Thank you very much.

**Comment by linnabrown** [comment]
I can't understand what do you mean "relative abundance results" ?
Could you explain it more specifically?

**Comment by HNUmcc** [comment]
Sorry, Professor Huang
I need a table that contains abundance information, rows for CAZy ID, and columns for samples ID for difference analysis.

**Comment by linnabrown** [comment]
If you need a more informative table like the example result, please go to our server version.
http://bcb.unl.edu/dbCAN2/
![sample_result_page](http://bcb.unl.edu/dbCAN2/static/images/result-page.png)
