### ISSUE TITLE
hmmscan-parser.py retaining multiple hits to same protein

### ISSUE THREAD

**Issue by adityabandla** [linnabrown/run_dbcan#27]
From what I understand, hmmscan-parser.py filters hits based on e-value <=1e-15 & coverage >=0.35
It should also retain only the best hit (based on lower e-value) when the same protein gets hits to multiple domains

But when I tested it today, it looks like its retaining all hits to a protein and not just the best hit

**Comment by linnabrown** [comment]
Could you please show your result which retains all hits?
Or give me your input to let me test it?

Thank you.

**Comment by adityabandla** [comment]
[1RBYCC.146.contigs.filtered.faa_out_domtbl.txt](https://github.com/linnabrown/run_dbcan/files/3829056/1RBYCC.146.contigs.filtered.faa_out_domtbl.txt)
Attached is the hmmsearch results (same as hmmscan)

**Comment by adityabandla** [comment]
On a separate note, is it possible to update the codebase to replace hmmscan with hmmsearch, the performance improved tremendously. I think this issue has been known for quite some time

**Comment by yinlabniu** [comment]
You can't use hmmsearch, because the hmmscan parser only works for hmmscan result. That's the reason that you didn't get correct output.
________________________________

**Comment by adityabandla** [comment]
[1NBY2RZPCC.16.contigs.filtered.faa_out_domtbl.txt](https://github.com/linnabrown/run_dbcan/files/3829059/1NBY2RZPCC.16.contigs.filtered.faa_out_domtbl.txt)
This is with hmmscan, issue seems to persist

**Comment by yinlabniu** [comment]
Can you show any evidence that hmmsearch improves the result? I don't personally agree that hmmsearch will be better. For example, a protein could hit different GH domains in the same region. If you do hmmscan, our parser will tell you which one has the best e-value. If you do hmmsearch, this protein will be assigned to all these GH families.
________________________________

**Comment by linnabrown** [comment]
This parser result is correct and reasonable. 

Firstly, we don't just retain one best hit. Because each protein could have multiple domains. It make sense. 

Secondly, as you see, the parser result does not retain all hits. It just filtered according to e-value <=1e-15 & coverage >=0.35. Under this threshold, it is reasonable that the protein BY2RZP_171014_20 can have a lot of domains.

We do not aim to retain only one best hit. You need to read our paper(https://academic.oup.com/nar/article/46/W1/W95/4996582) and refer to our website (http://bcb.unl.edu/dbCAN2) to understand our tools.

Thank you for using our tools.

**Comment by linnabrown** [comment]
If you think these thresholds are too big, which let some protein retain a lot of hits,  you could change the them by add params like `--hmm_eval 1e-17 ` and `--hmm_cov 0.50` n order to change the e-value and coverage respectively when using run_dbcan.py.

**Comment by adityabandla** [comment]
@linnabrown Thanks for taking the time to help out with this, I appreciate it
These were the comments from the origing hmmscan-parser script
```
# 1. take hmmer3 output and generate the tabular output
# 2. sort on the 6th and 7th cols
# 3. remove overlapped/redundant hmm matches and keep the one with the lower e-values
# 4. calculate the covered fraction of hmm (make sure you have downloaded the "all.hmm.ps.len" file to the same directory of this perl script)
# 5. apply the E-value cutoff and the covered faction cutoff
```
I assume the hmmscan-parser.py script follows the same logic and thus follows comment #3

**Comment by yinlabniu** [comment]
Yes, it follows the logic of the old script and does the same thing and only parses hmmscan result.
________________________________

**Comment by adityabandla** [comment]
@linnabrown @yinlabniu Many thanks for your time and patience, I now get the hang of what the script is actually doing

**Comment by SergeyBaikal** [comment]
Dear Authors! Thank you for the parser!
As far as I understand this parser can be used with the file --domtblout from hmmscan.

`python hmmscan_parser.py /home/HMMER3/My_data/Results.txt 1e-150 0.90 > best_results.txt`

I have a question. Why do I get the same results even with very strong parameters? The help is not prescribed in the script, am I entering the parameters correctly?
