### ISSUE TITLE
some minor problems in the updated run_dbcan.py

### ISSUE THREAD

**Issue by Li-Dongyao-ancore** [linnabrown/run_dbcan#30]
Glad for your reply to my email. After reading the updated version of code, I found some minor problems still remaining, so I issued a pull request.

**Comment by linnabrown** [comment]
Thank you for your suggestion and contribution.  We have combined your codes into our project.

**Comment by Li-Dongyao-ancore** [comment]
line 329, maybe it should be "cazyme_genes[row[0]].update()"
add() will bring a type error: unhashable type: 'set'

**Comment by linnabrown** [comment]
> cazyme_genes

Thank you very much! It has been corrected now.
