### ISSUE TITLE
Mis-spelling "comlete" should be "complete"

### ISSUE THREAD

**Issue by dadahan** [linnabrown/run_dbcan#33]
https://github.com/linnabrown/run_dbcan/blob/0ee6f21f8b61940743bbcfcc1d3184968b631c7b/run_dbcan.py#L140

**Comment by linnabrown** [comment]
Thanks:)

**Comment by dadahan** [comment]
Also, the line was breaking because of the spaces in the subprocess call but when I switched it to below where there are no spaces after flags and their parameters it worked. 

`call(['FragGeneScan', '-s', input, '-o', '%sfragGeneScan'%outPath,'-w','1','-t','complete','-p','10'])`

**Comment by linnabrown** [comment]
Good eye. Thank you very much!
