### ISSUE TITLE
Suggestion to change "Gene ID" column name in overview.txt

### ISSUE THREAD

**Issue by Lamm-a** [linnabrown/run_dbcan#36]
Is it possible for you to change the column name of "Gene ID" in the overview.txt files to be "Gene_ID" This would make reading into pandas or dataframe handeling systems eaiser as I believe the file is delinimated by different characters and thus something such as `sep=r'\s{1,}'` much be used in pandas which then splits "Gene" and "ID" into two seperate column names.

**Comment by linnabrown** [comment]
set `sep="\t"` in your pandas.read_csv().
