### ISSUE TITLE
Annotation conflict from CAZyme and TC

### ISSUE THREAD

**Issue by Li-Dongyao-ancore** [linnabrown/run_dbcan#42]
Hello Linna,

Recently I found that in the run_dbcan+CGCFinder pipleline if a protein was simultaneously annotated as a CAZyme and transporter, the CAZyme annotation would be overwritten by the TC annotation. For example, protein WP006295915.1 was once annotated as GH13 (34-381, Evalue=1.1e-63, Coverage=0.93) and TC-DB|Q07837|8.A.9.1.2 (11-545, Evalue=4.0e-43, Pident=27.4%), but in the final CGCFinder output file it was only presented as a TC.

I think this problem is caused by the GFF preperation codes in run_dbcan.py (line 412-420) where the elif for CAZyme is behind the elif for TC. I suggest to change the logical structure herein to avoid loss of annotation information.

Best, 

Dongyao Li

**Comment by Li-Dongyao-ancore** [comment]
Sorry, it should be run_dbcan.py (line 455-463).

**Comment by linnabrown** [comment]
This is a good question. We will discuss this problem ASAP and give you the feedback.

**Comment by yinlabniu** [comment]
@Li-Dongyao-ancore Thanks for catching this issue (not a bug). I agree with you that in the example you gave, we should choose CAZyme over TC, not only because the e-value and cov are better, but also because TCDB has lower data quality than CAZy. Yes, we will make this change in the code.

**Comment by linnabrown** [comment]
@Li-Dongyao-ancore  This issue has been solved in 2.0.9 verision.

**Comment by Li-Dongyao-ancore** [comment]
Cool 👍
