### ISSUE TITLE
HotPep temp dir

### ISSUE THREAD

**Issue by sjanssen2** [linnabrown/run_dbcan#44]
when executing `run_dbcan.py` a directory `HotPep` with a file `temp` is created in the current working directory. This causes issues if run_dbcan.py is executed parallel on multiple input files.
I would expect that this file is created in the output directory. Is it possible to change this behaviour?

**Comment by sjanssen2** [comment]
I figure this here is the problematic line in the main script: https://github.com/linnabrown/run_dbcan/blob/829c63b3c222a6f08afde7b0cddba2fcf2a4e617/run_dbcan.py#L197

**Comment by sjanssen2** [comment]
I further traced the issue and found this line https://github.com/linnabrown/run_dbcan/blob/829c63b3c222a6f08afde7b0cddba2fcf2a4e617/Hotpep/bact_group_many_proteins_many_patterns.py#L157
Why is that necessary? Where is this file used again?

**Comment by sjanssen2** [comment]
if used with multiple cores, I fear that the `temp` file is concurrently overwritten in the order of thread completeness.

**Comment by linnabrown** [comment]
Hi sjassen2, thank you very much for your attention. `temp` is not a useful file which is left in the old code(you can search `temp` in github). So this is not an issue. I will delete this line.

**Comment by linnabrown** [comment]
v2.0.10 solved this problem.

**Comment by szzxpxf** [comment]
I ran into the same issue. Thanks for posting this.

**Comment by linnabrown** [comment]
> I ran into the same issue. Thanks for posting this.

we don't have this issue now, thanks
