### ISSUE TITLE
CGC-Finder Error: list index out of range

### ISSUE THREAD

**Issue by szzxpxf** [linnabrown/run_dbcan#45]
Dear developer, 
I can run the dbCAN2 tool without any issue when not using the CGC finder. However, when I specify a gff file with the "-c" option, I got the following error:

*****************************CGC-Finder start************************************
Traceback (most recent call last):
  File "~/miniconda3/envs/run_dbcan/bin/run_dbcan.py", line 391, in <module>
    notes[temp[0]] = temp[1]
IndexError: list index out of range

Could you let me know what I can do to fix this?

Thank you!

**Comment by linnabrown** [comment]
@szzxpxf  What does the last column of your gff file look like? We assume that your input gff file is the standard gff3 format. That is, the last column is {key}={value};{key}={value};...

**Comment by szzxpxf** [comment]
This is the last field of my gff file:
ID=1_1;partial=00;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.291;conf=100.00;score=98.24;cscore=100.55;sscore=-2.31;rscore=-4.86;uscore=-0.38;tscore=2.93;

**Comment by szzxpxf** [comment]
It's generated from prodigal. Do I need to trim down the number of fields? Or do you recommend another gene-calling tool? These are metagenome-assembled genomes.

**Comment by linnabrown** [comment]
delete the ";" at the end of the  in you gff file solve this problem.

**Comment by linnabrown** [comment]
```
pip install run-dbcan==2.0.11
```

to save your life. I solve the prodigal problem now.

**Comment by szzxpxf** [comment]
Thanks so much for fixing this!!!
I could have delete the extra ; at the end of the gff file. 
I'm sure many other future users will benefit from this update in case they have gff generated from prodigal!

**Comment by Rob-murphys** [comment]
This error has come up again from `GFF` format files created by prodigal.
