### ISSUE TITLE
CGCFinder output header

### ISSUE THREAD

**Issue by sandragodinhosilva** [linnabrown/run_dbcan#46]
Hi.
I'm having difficulties in understanding the contents of CGC output file. Do you have any template output that describes what is on each column? Or do you plan to include an header?

Many thanks for providing the tool.

**Comment by linnabrown** [comment]
```
geneNumber signature_gene_type downDistance upDistance CGC_number contig[0] geneStart[3] geneEnd[4] geneID[8,ID] direc[6] note[8]
```

**Comment by sandragodinhosilva** [comment]
Many thanks!
