### ISSUE TITLE
hmmscan not effective, use hmmsearch?

### ISSUE THREAD

**Issue by erikrikarddaniel** [linnabrown/run_dbcan#49]
Hi,

I'm running `run_dbcan` on a large set of ORFs and it takes forever (10 days at the moment). Moreover, it doesn't use more than one thread although I've specified 4. In an old blog post, Sean Eddy explains why `hmmscan` is slow and that one should use `hmmsearch` instead (https://cryptogenomicon.org/2011/05/27/hmmscan-vs-hmmsearch-speed-the-numerology/; this is about translated nucleotide searches, but I believe it applies well to ORFs in amino acid format too). My suggestion is hence: Would you consider changing to `hmmsearch`, or can you give me suggestions for how to manually run classifications with `hmmsearch`? (I know dbcan distributes profiles via a packed repository which doesn't work with `hmmsearch` but maybe there's a way around that.)

/D

**Comment by yinlabniu** [comment]
Hi Daniel,

There is no problem in running hmmsearch with dbCAN hmms as query and seq fasta as db from user's perspective. However, making this change will create a chain of complications for our run_dbcan package. It is likely that hmmsearch will give different result (maybe not major) than hmmscan because the db and query are switched. Also the hmmscan parser within run_dbcan needs some change. All the optimal parameters (e-value and coverage) that were benchmarked need to be redone, which won't be easy.

So my suggestion is that you partition your fasta file into 10 or 100 smaller files, and run them in parallel.

Yanbin

________________________________

**Comment by erikrikarddaniel** [comment]
OK, thanks for the reply.

/Daniel

**Comment by singhbhavya** [comment]
Hi @erikrikarddaniel, 

I know this is an old thread, so I am very sorry for bothering you. I was wondering if you were able to find a way to make hmmscan run faster? I'm in a similar situation, where I need to run dbcan on a few thousand files, and hmmscan is definitely slowing things down. Did you partition your fasta files into smaller files to run in parallel, or is there something else you were able to do? 

Thank you so much!

Bhavya

**Comment by erikrikarddaniel** [comment]
Hi @singhbhavya,

I actually don't remember what I did, but partitioning fasta files is easy so it seems likely that's what I did.

Best would of course be if one could extract the individual hmm files from the package and then run hmmsearch manually but I haven't found out how.

/D

**Comment by erikrikarddaniel** [comment]
Hi again @singhbhavya,

By accident I came across the directory where I had done this and I had actually left a note:

"""
Because of the very large number of sequences in BARM, I ran `run_dbcan.py` on
293 separate fasta files with sequences, each with its own directory with
results. I deleted these directories after creating an archive,
`BARM.dbcan.individual_runs.tar`, with all the contents.
"""

We're running on a cluster, so I submitted six jobs, each of them running 20 parallel sessions of dbcan scanning (I used make to parallelize, i.e. -j 20). Each file contained about 10,000 ORF sequences and took about 2 h to scan.

/D

**Comment by singhbhavya** [comment]
Hi @erikrikarddaniel,

This was IMMENSELY helpful!!! Thank you so much! I did what you said, and everything is so much faster! I think this was initially going to take a month to run, but now it should be done in a few days. 😄  Thank you again for taking the time to respond to me!
