### ISSUE TITLE
dbcan with unassembled metagenomic sequence

### ISSUE THREAD

**Issue by Shriram369** [linnabrown/run_dbcan#51]
Hi dbcan dev, 

I really appreciate your effort making this tool open source for the community.

Actually, we have 150*2 paired end shotgun sequenced data and we think assembling more than 500+ samples would take enormous amount of out time.

In that case, would it be wise enough to use unassembled metagenomic sequences (short reads) to profile CaZYmes using this pipeline? 

Appreciate your advice on this.

Shriram

**Comment by yinlabniu** [comment]
Hi Shriram,

Thanks for the question. I do not recommend to use run_dbcan on the unassembled reads, because it simply won't work (the first step gene prediction will fail to produce meaningful protein sequences). Actually, another user had a similar request as yours. Raw read-based CAZyme annotation is possible, but needs substantial redesign of our pipeline, which most likely will lead to an entirely new software package. I will have one student to take on this project in the summer and hopefully will have a new tool available in a few months.

Yanbin
________________________________

**Comment by Shriram369** [comment]
Thank you very much for your prompt feedback.

Also it would be worth taking your feedback/ suggestions on performing translated search (diamond blastx; taking into account all six putative frames) against "CAZyDB.07312019.fa.nr"?

Really looking forward for the tool. 

Shriram

**Comment by yinlabniu** [comment]
Yes, diamond blastx should work but you might want to use a very stringent e-value, identity, and coverage threshold in parsing the result.

Yanbin

________________________________

**Comment by Shriram369** [comment]
Perfect, thanks for your feedback.

**Comment by Shriram369** [comment]
Hi Yanbin, 

I have a (silly) follow-up question in the line with the discussion of performing diamond blastx search with short read metagenomic sequences. Hope your insights in this will also help other dbcan users as well.

I am planning to use non redundant version of CAZy reference (CAZyDB.07312019.fa.nr) database in blastx search followed by stringent parsing of the alignment results as per your suggestion. But on closer inspection of the database, I have found that some of the sequences are annotated with multiple CAZy families.

For example one of the reference sequence is annotated with both GT0 and GT2 (>BBL34982.1|GT0|GT2|). So, when parsing the alignment results, should we provide one count each to GT0 and GT2 or just to GT0? or any other recommended approach?

Thank you.

Shriram

**Comment by yinlabniu** [comment]
> Hi Yanbin,
> 
> I have a (silly) follow-up question in the line with the discussion of performing diamond blastx search with short read metagenomic sequences. Hope your insights in this will also help other dbcan users as well.
> 
> I am planning to use non redundant version of CAZy reference (CAZyDB.07312019.fa.nr) database in blastx search followed by stringent parsing of the alignment results as per your suggestion. But on closer inspection of the database, I have found that some of the sequences are annotated with multiple CAZy families.
> 
> For example one of the reference sequence is annotated with both CBM26 and GH13-28 (>ADM36368.1|CBM26|GH13_28|). So, when parsing the alignment results, should we provide one count each to CBM26 and GH13-28? or any other recommended / suggested approach?
> 
> Thank you.
> 
> Shriram

**Comment by yinlabniu** [comment]
Sorry for the late response. If you do blastx search, take the best cazy hit for each read. Then when count how many reads match a cazy hit, you want to consider all the domains for each cazy hit. For the example you give, you would add a count each to CBM26 and GH13-28.

Yanbin
