### ISSUE TITLE
pip install run-dbcan==2.0.11 not working

### ISSUE THREAD

**Issue by Juliana-Soto24** [linnabrown/run_dbcan#53]
Hi, 
I'm trying to install run-dbcan in aws but I'm getting this error: 
pip install run-dbcan==2.0.11
ERROR: Could not find a version that satisfies the requirement run-dbcan==2.0.11 (from versions: none)
ERROR: No matching distribution found for run-dbcan==2.0.11

Thanks, 

Juliana

**Comment by linnabrown** [comment]
Seems strange. Mine works.

```
(base) ➜  ~ pip install run-dbcan==2.0.11
Collecting run-dbcan==2.0.11
  Downloading https://files.pythonhosted.org/packages/ae/87/431b9b651544ead5b0889c39e6fddb9e1dd98e773c2ed5c229e18e063ee6/run_dbcan-2.0.11.tar.gz (5.7MB)
     |████████████████████████████████| 5.7MB 1.1MB/s
Requirement already satisfied: natsort in ./anaconda3/lib/python3.7/site-packages (from run-dbcan==2.0.11) (7.0.1)
Requirement already satisfied: setuptools in ./.local/lib/python3.7/site-packages (from run-dbcan==2.0.11) (41.6.0)
Building wheels for collected packages: run-dbcan
  Building wheel for run-dbcan (setup.py) ... done
  Stored in directory: /Users/huangle/Library/Caches/pip/wheels/06/04/41/3b050f81e4cc7c98519255ac0481999c7144914d8e518840ba
Successfully built run-dbcan
Installing collected packages: run-dbcan
  Found existing installation: run-dbcan 2.0.8
    Uninstalling run-dbcan-2.0.8:
      Successfully uninstalled run-dbcan-2.0.8
Successfully installed run-dbcan-2.0.11
```

**Comment by linnabrown** [comment]
Did you run the following codes first?

```
conda create -n run_dbcan python=3.8 diamond hmmer prodigal -c conda-forge -c bioconda
conda activate run_dbcan
```

**Comment by Juliana-Soto24** [comment]
Yes, I did

It seems that it was a problem with the pip version on the EC2.

Now it’s running and I got this message:

The host system is detected to have 63 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b6

I was wondering if you could please explain how can I increase the block size?

Thanks,

Juliana

**Comment by linnabrown** [comment]
Your problem is out of our range because this is your own platform problem. However, I guess you are using AWS EC2 right?

If you do so, you can resize your instance disk ratio up to 500 GB on the cloud by yourself just like google cloud vm instance.

Also, you mentioned 


```
It seems that it was a problem with the pip version on the EC2.
```

This should not the problem of pip version once you installed anaconda, create dbcan virtual env and then activate it you will get the pip version as 3.8 and python also 3.8.
