### ISSUE TITLE
Skip the prodigal step?

### ISSUE THREAD

**Issue by BinhongLiu** [linnabrown/run_dbcan#54]
Dear Pro. Yin,
    Thanks for the development of this useful tool!
    Now I've built a non-redundant gene catalogue (DNA .fasta file) with my metagenomic data. I'm wondering if it possible to run dbcan2 annotation directly without the first prodigal prediction step? Because different ORFs might be found between the tool I used and the prodigal within dbcan2. I've tried to delete the prodigal-related code within the _run_dbcan.py_ script, but I failed. Could you help me with this problem? Many thanks!
Best wishes!
Hongbin Liu

**Comment by linnabrown** [comment]
Our code intends to get the protein data input. If your data is DNA, we will use prodigal to predict its protein sequences. 
You can use your method to converge your DNA data into proteins, and then use the following code to run our tool like this command:

```
run_dbcan.py EscheriaColiK12MG1655.faa protein -c EscheriaColiK12MG1655.gff --out_dir output_EscheriaColiK12MG1655

```
