### ISSUE TITLE
--cgc_sig_genes {tp,tf,all}

### ISSUE THREAD

**Issue by LuDeChen** [linnabrown/run_dbcan#55]
Thanks for develop so cool pipline. I have a question when I use this pipline. When I use this pipline.  I wonnder know this commond's fault about "--cgc_sig_genes {tp,tf,all}" It is tp? tf? or all?  
Thanks very much!

**Comment by linnabrown** [comment]
default='tp'

**Comment by LuDeChen** [comment]
Thanks for your reply, I have another question,
I have a issue running the command

run_dbcan.py AGCM10006840.faa protein -c AGCM10006840.gff --out_dir AGCM10006840 --db_dir /bioinf/home/software/db/

All the processes seem to have no problems, but when the program runs to completion, an error message appears.
“The host system is detected to have 3245 GB of RAM. It is recommended to increase the block size for better performance using these parameters: -b12 -c1
Traceback (most recent call last):
File "/bioinf/home/dlu/miniconda3/envs/run_dbcan/bin/run_dbcan.py", line 385, in
if row[2] == "CDS":
IndexError: list index out of range”

In the output folder exists the files: Hotpep.out, cgc.gff, diamond.out, hmmer.out, stp.out, tf-1.out, tf-2.out, tp.out, uniInput.

could you told me how to solve this problem.

**Comment by linnabrown** [comment]
https://github.com/linnabrown/run_dbcan/issues/67#issuecomment-801169358
