### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by catrinehom** [linnabrown/run_dbcan#57]
Dear dbcan team,

I have cloned this directory, and I am trying to use your tool. I am trying with your test files, e.g. running the command "./run_dbcan.py EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655". 

However, I am getting this error:

  File "train_many_organisms_many_families.py", line 11, in <module>
    from Hotpep.hotpep_data import hotpep_data_path
ModuleNotFoundError: No module named 'Hotpep'

I am using Python 3.6.10. 

I have also had the following problems: 

***************************2. HMMER end***************************************************
/bin/sh: hmmscan-parser.py: command not found
***************************3. HotPep start***************************************************
sh: train_many_organisms_many_families.py: command not found

But I have solved those, by putting the full path into the run_dbcan.py script. This might be related, however.

Best regards,
Catrine Høm

**Comment by catrinehom** [comment]
I have now tried making an env specifically for this, and done the pip install instead of cloning the Github, but I still get the same error.

**Comment by catrinehom** [comment]
By trying again and again, I found this error, when making the db:

`bash: hmmpress: command not found...
`

Making me realise you need diamond and hmmer already when making the db, not only when running the tool.  Fixing this, it now works.

**Comment by linnabrown** [comment]
Yes. Do not use git clone method. Use the install usage and follow the step one by one.
