### ISSUE TITLE
gff parsing

### ISSUE THREAD

**Issue by catrinehom** [linnabrown/run_dbcan#58]
Hi run_dbcan team!

Apparently, I have a slightly difference format of .gff file, than you usually use. Mine is the output from the use of PROKKA. This gives me an error in line 385 in your run_dbcan.py script (if row[2] == "CDS":), since some of my first lines in the gff file are not long enough when using the split by tab! This will exit the whole pipeline. 

I have fixed this by adding a try/except around that if statement, and it seems like the rest of the pipeline works then.

Best regards, 
Catrine

**Comment by linnabrown** [comment]
Thanks! Welcome to PR for your contribution.

**Comment by iaunicorn** [comment]
Hi,
 
I also have a problem with the .gff file.  The last column of my .gff looks like: 
           name "AN5093"; proteinId 1; exonNumber 1 (it is very short).
It gives me an error in line 391 in your run_dbcan.py script:
           notes[temp[0]] = temp[1]
           IndexError: list index out of range
So how should I fix it according to my format of .gff file. I am not sure about what's the role of this script.
Thanks in advance.

Best wishes,
Jia

**Comment by catrinehom** [comment]
I think the same solution that I used would help you. So go to line 386 in run_dbcan.py, and replace:

                            if row[2] == "CDS":
                                note = row[8].strip().rstrip(";").split(";")
                                gene = ""
                                notes = {}
                                for x in note:
                                    temp = x.split('=')
                                    notes[temp[0]] = temp[1]
                                if "Name" in notes:
                                    gene = notes["Name"]
                                elif "ID" in notes:
                                    gene = notes["ID"]
                                else:
                                    continue
                                
                                if gene in cazyme:
                                    row[2] = "CAZyme"
                                    row[8] = "DB="+'|'.join(cazyme_genes[gene])
                                elif gene in tf:
                                    row[2] = "TF"
                                    row[8] = "DB="+tf_genes[gene]
                                elif gene in tp:
                                    row[2] = "TC"
                                    row[8] = "DB="+tp_genes[gene]
                                elif gene in stp:
                                    row[2] = "STP"
                                    row[8] = "DB=" + stp_genes[gene]
                                else:
                                    row[8] = ""
                                row[8] += ";ID="+gene
                                out.write('\t'.join(row)+'\n')

with: 
                            try:
                                if row[2] == "CDS":
                                    note = row[8].strip().rstrip(";").split(";")
                                    gene = ""
                                    notes = {}
                                    for x in note:
                                        temp = x.split('=')
                                        notes[temp[0]] = temp[1]
                                    if "Name" in notes:
                                        gene = notes["Name"]
                                    elif "ID" in notes:
                                        gene = notes["ID"]
                                    else:
                                        continue
                                
                                    if gene in cazyme:
                                        row[2] = "CAZyme"
                                        row[8] = "DB="+'|'.join(cazyme_genes[gene])
                                    elif gene in tf:
                                        row[2] = "TF"
                                        row[8] = "DB="+tf_genes[gene]
                                    elif gene in tp:
                                        row[2] = "TC"
                                        row[8] = "DB="+tp_genes[gene]
                                    elif gene in stp:
                                        row[2] = "STP"
                                        row[8] = "DB=" + stp_genes[gene]
                                    else:
                                        row[8] = ""
                                    row[8] += ";ID="+gene
                                    out.write('\t'.join(row)+'\n')
                            except:
                                print(row+' skipped')

**Comment by iaunicorn** [comment]
Hi catrinehom,

Thanks so much for your help. I tried to use your solution, but it didn't work. 
>notes[temp[0]] = temp[1]
IndexError: list index out of range
>print(row+' skipped')
TypeError: can only concatenate list (not "str") to list.

**Comment by catrinehom** [comment]
Did you add the "try" and "except"?

I have also now edited the last line to: "print('row skipped')".

**Comment by iaunicorn** [comment]
Yes, I did.
I think my .gff format looks like this:
ChrIII      J     exon    19      657     .       +       .       name "AN5093"; transcriptId 181
ChrIII       J     CDS     19      657     .       +       0       name "AN5093"; proteinId 1; exonNumber 1
ChrIII       J     start_codon     19      21      .       +       0       name "AN5093"
ChrIII       J     exon    698     831     .       +       .       name "AN5093"; transcriptId 181
ChrIII       J     CDS     698     831     .       +       0       name "AN5093"; proteinId 1; exonNumber 2

so it can't split correctly by using the following scripts (I think it was the problem):
                                for x in note:
                                    temp = x.split('=')
                                    notes[temp[0]] = temp[1]
                                if "Name" in notes:
                                    gene = notes["Name"]
                                elif "ID" in notes:
                                    gene = notes["ID"]
                                else:
                                    continue

**Comment by catrinehom** [comment]
Yes, I also think it is a split problem. However, I sadly don't have anymore suggestion for you.

**Comment by iaunicorn** [comment]
Anyway, thank you so much.
I will try to transfer my gff format into the format this tool needs.
