### ISSUE TITLE
Possible to use conda installation with v9 databases?

### ISSUE THREAD

**Issue by justinshaffer** [linnabrown/run_dbcan#59]
Hello,

I hope this note finds you well.

I am planning to use the conda installation of your tool, but notice that the installation documentation here does not include the v9 databases but uses v8. Is it possible to use the conda installation with the v9 database obtained from the link below?

http://bcb.unl.edu/dbCAN2/download/

Thanks in advance,

Justin Shaffer

**Comment by linnabrown** [comment]
Yes you can revise v8 to v9
