### ISSUE TITLE
CGC finder issue

### ISSUE THREAD

**Issue by Russel88** [linnabrown/run_dbcan#6]
Hi

I get the following error when I use the input from prokka to run run_dbcan:

Traceback (most recent call last):
  File "run_dbcan.py", line 429, in <module>
    if row[2] == "CDS":
IndexError: list index out of range

I ran it like this;
python run_dbcan.py X.faa protein -c X.gff --out_dir X

**Comment by linnabrown** [comment]
Hi, I am not familiar with prokka, could you show me the example of input?

**Comment by Russel88** [comment]
I found the problem.

In the output of prokka the sequences are added to the end of the gff file. If I remove that, the script runs fine.
