### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'CGCFinder.py'

### ISSUE THREAD

**Issue by justinshaffer** [linnabrown/run_dbcan#60]
Hello,

Thank you for previously confirming that I can use the v9 databases with the conda installation of your tool. I have run into another issue.

When running the command below, I run into the following error. I am running the most recent version from the conda installation.

Code:
run_dbcan.py \
  EscheriaColiK12MG1655.fna \
  prok \
  --out_dir example/ \
  --cluster example/EscheriaColiK12MG1655.gff \
  --tools 'all' \
  --dbCANFile dbCAN-HMMdb-V9.txt \
  --dia_cpu 16 \
  --hmm_cpu 16 \
  --hotpep_cpu 16 \
  --tf_cpu 16 \
  --out_pre output_EscheriaColiK12MG1655 \
  --db_dir software/dbcan2/databases/v9/

Output before error:
CGC-Finder start
diamond v2.0.5.143 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /home/jpshaffer/software/dbcan2/example
Opening the database...  [0.016s]
#Target sequences to report alignments for: 1
Reference = /home/jpshaffer/software/dbcan2/databases/v9/tcdb.dmnd
Sequences = 14465
Letters = 6343638
Block size = 2000000000
Opening the input file...  [0.002s]
Opening the output file...  [0.001s]
Loading query sequences...  [0.014s]
Masking queries...  [0.119s]
Building query seed set...  [0.013s]
The host system is detected to have 270 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b8 -c1
Algorithm: Double-indexed
Building query histograms...  [0.036s]
Allocating buffers...  [0s]
Loading reference sequences...  [0.023s]
Masking reference...  [0.41s]
Initializing temporary storage...  [0.028s]
Building reference histograms...  [0.204s]
Allocating buffers...  [0s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 1/4.
Building reference seed array...  [0.118s]
Building query seed array...  [0.025s]
Computing hash join...  [0.029s]
Building seed filter...  [0.002s]
Searching alignments...  [0.062s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 2/4.
Building reference seed array...  [0.143s]
Building query seed array...  [0.031s]
Computing hash join...  [0.029s]
Building seed filter...  [0.002s]
Searching alignments...  [0.054s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 3/4.
Building reference seed array...  [0.128s]
Building query seed array...  [0.025s]
Computing hash join...  [0.022s]
Building seed filter...  [0.001s]
Searching alignments...  [0.039s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 4/4.
Building reference seed array...  [0.085s]
Building query seed array...  [0.018s]
Computing hash join...  [0.022s]
Building seed filter...  [0.001s]
Searching alignments...  [0.038s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 1/4.
Building reference seed array...  [0.085s]
Building query seed array...  [0.018s]
Computing hash join...  [0.022s]
Building seed filter...  [0.001s]
Searching alignments...  [0.041s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 2/4.
Building reference seed array...  [0.109s]
Building query seed array...  [0.023s]
Computing hash join...  [0.022s]
Building seed filter...  [0.001s]
Searching alignments...  [0.039s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 3/4.
Building reference seed array...  [0.115s]
Building query seed array...  [0.025s]
Computing hash join...  [0.022s]
Building seed filter...  [0.002s]
Searching alignments...  [0.039s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 4/4.
Building reference seed array...  [0.085s]
Building query seed array...  [0.018s]
Computing hash join...  [0.022s]
Building seed filter...  [0.002s]
Searching alignments...  [0.038s]
Deallocating buffers...  [0.002s]
Clearing query masking...  [0s]
Computing alignments...  [0.782s]
Deallocating reference...  [0.001s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0s]
Deallocating queries...  [0s]
Loading query sequences...  [0s]
Closing the input file...  [0s]
Closing the output file...  [0.002s]
Closing the database file...  [0s]
Deallocating taxonomy...  [0s]
Total time = 3.292s
Reported 1071 pairwise alignments, 1071 HSPs.
1071 queries aligned.
The host system is detected to have 270 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b8 -c1

Error:
Traceback (most recent call last):
  File "/home/jpshaffer/software/miniconda3/bin/run_dbcan.py", line 448, in <module>
    call(['CGCFinder.py', outDir+prefix+'cgc.gff', '-o', outDir+prefix+'cgc.out', '-s', args.cgc_sig_genes, '-d', str(args.cgc_dis)])
  File "/home/jpshaffer/software/miniconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/jpshaffer/software/miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jpshaffer/software/miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'CGCFinder.py'

This error indicates that 'CGCFinder.py' is not present, however when I run 'which' it seems to be found:
$ which CGCFinder.py
~/software/miniconda3/bin/CGCFinder.py

Have you seen something like this before? Any ideas how to resolve this problem?

Thanks in advance,

Justin Shaffer

**Comment by linnabrown** [comment]
no

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by justinshaffer** [comment]
I was able to resolve the issue by adding the full path to the CGCFinder.py file in the run_dbcan.py file, at line 448.

Thank you,

Justin Shaffer
