### ISSUE TITLE
More explanations of the output files

### ISSUE THREAD

**Issue by iaunicorn** [linnabrown/run_dbcan#61]
Hi,
Thanks for developing such a great pipeline. Could you provide more explanations about the output files?
I got the following results:
cgc.gff
cgc.out
diamond.out
hmmer.out
Hotpep.out
overview.txt
stp.out
tf-1.out (?)
tf-2.out (?)
tp.out (?)
uniInput

I did not get the explanations of output files marked with ?.
Thanks in advance.

**Comment by linnabrown** [comment]
tf-1 tf-2 and tp.out are middle file from hmmscan for searching tf-1,2 and tp database. You can ignore them because they are middle files.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iaunicorn** [comment]
Thanks so much.

**Comment by maracashay** [comment]
I'm going to jump in on this thread because I also would like to have more information about the overview.txt file. Enzymes are presented as "GH23(3-117)" for HMMER and "GH23(208)" for Hotpep. What do the values in the () for HMMER and Hotpep refer to?

Thanks!

**Comment by yinlabniu** [comment]
GH23(3-117) means the GH23 domain starts at 3 and ends at 117, according to hmmer against dbCAN HMMdb.

Hotpep predicts CAZymes using a different algorithm. GH23(208) means hotpep thinks the query is a GH23 and subfam 208. Note this subfamily 208 has nothing to do with CAZy's subfam. CAZy only has subfam info for about less than 30 CAZyme families, while PPR (which is hotpep's database) has classified all CAZyme families into subfamilies and these subfam IDs do not match with CAZy's 30 families. More info can be found in the Hotpep.out file.

Yanbin

________________________________________

**Comment by maracashay** [comment]
Great. Thank you so much!
