### ISSUE TITLE
Error running .fna files

### ISSUE THREAD

**Issue by edisagarcia** [linnabrown/run_dbcan#65]
Hi! 
Thanks for developing this useful tool.
I have a issue running the command 

run_dbcan.py nucleotides22.fna meta --hmm_cpu 16 --tools all --out_dir ./cazy22c

In the output folder exists the files 
prodigal.gff 
uniInput and  
an empty overview.txt.

The program stops and the last text is:

The following have been reloaded with a version change:
  1) GCCcore/6.4.0 => GCCcore/9.3.0

Preparing overview table from hmmer, hotpep and diamond output...
overview table complete. Saved as ./cazy39c/overview.txt

What can I do?

Thanks in advance for any help.

**Comment by linnabrown** [comment]
cazy22c not ./cazy22c
