### ISSUE TITLE
if row[2] == "CDS"

### ISSUE THREAD

**Issue by LuDeChen** [linnabrown/run_dbcan#67]
Hi!
Thanks for developing this cool tool.
I have a issue running the command

run_dbcan.py AGCM10006840.faa protein -c AGCM10006840.gff --out_dir AGCM10006840 --db_dir /bioinf/home/software/db/

All the processes seem to have no problems, but when the program runs to completion, an error message appears. 
“The host system is detected to have 3245 GB of RAM. It is recommended to increase the block size for better performance using these parameters: -b12 -c1
Traceback (most recent call last):
  File "/bioinf/home/dlu/miniconda3/envs/run_dbcan/bin/run_dbcan.py", line 385, in <module>
    if row[2] == "CDS":
IndexError: list index out of range”

In the output folder exists the files: Hotpep.out, cgc.gff, diamond.out, hmmer.out, stp.out, tf-1.out, tf-2.out, tp.out, uniInput. 

How to solve this problem.

**Comment by linnabrown** [comment]
It seems that your `AGCM10006840.gff` have some rows which does not have 9 columns separated by `\t`. Please make sure each row of your gff file have9 fields separated by `\t`.

**Comment by LuDeChen** [comment]
Thanks for your reply!

**Comment by LuDeChen** [comment]
I still have a question.
when I use the tool. I only want use two method diamond and hmmer to do the blast. but the hmmer.out is empty. could you give me some advise, this is my commond.
run_dbcan.py RZ0.faa protein -c RZ0.gff --out_dir RZ04 --db_dir /bioinf/home/dlu/software/db/ -t diamond hmmer --dia_cpu 4 --dia_eval 1e-20 --hmm_cpu 4 --hmm_eval 15 --hmm_cov 30
And for the diamond, could we set parameters about cov , if we couldn't, could you tell me the defaults?

Thanks very much.

**Comment by linnabrown** [comment]
Default diamond coverage is the diamond default package. We did not change it. Please check the original diamond package

http://gensoft.pasteur.fr/docs/diamond/0.8.29/diamond_manual.pdf
