### ISSUE TITLE
Questions about running time and different version of the same cazy families

### ISSUE THREAD

**Issue by Anqi-Dai** [linnabrown/run_dbcan#68]
Hi Le,

I was wondering what is the running time like for a shotgun sample of about 20 million reads?
It seems taking forever (more than 30 hours at least) even running on 16 threads.
Subsampling seems to be the way to go?

Also I look at the results files, for GH13, there is GH13_5, GH13_7, GH13_8, etc. Can I just treat them as GH13 broadly and ignore the trailing 5,7,8 etc...?

Thank you 

Angel

**Comment by linnabrown** [comment]
It depends on the power of your computer/server to run db an. We have some cpu parameters interfaces for you to set. If you have a cluster that would be more helpful for you to run your 30M reads.

If you only want GH13 and not it's subfamily (gh13_1, gh13_2) you can just ignore the suffix. Thank you for using our tool.

**Comment by yinlabniu** [comment]
Thank you, Le.

Another note: current run_dbcan is designed for assembled contigs, so raw reads are not recommended to run through the tool.

Yanbin

________________________________________

**Comment by Anqi-Dai** [comment]
Hi Yanbin,
Thank you for making this point.
It's very important to know. I wonder if it could be specified somewhere in the github page so that people would know .....
Angel

**Comment by linnabrown** [comment]
Hi Anqi,
Thank you for your suggestion, I have added this information to the description.
