### ISSUE TITLE
Questions about results

### ISSUE THREAD

**Issue by Anqi-Dai** [linnabrown/run_dbcan#69]
Hi Le,
Very happy to have got results after switching from metagenomic reads to assembled contigs.

Several questions:
1. What does this kind of combination like CBM50+GH73 stand for? Do I count them as two separately?
2. If for a gene, only CBM50 is identified by 3 tools at the same time, and GH73 is by 2. Do I count CBM50 as reliably a cazyme?

Angel

**Comment by linnabrown** [comment]
1. CBM50+GH73 stands for two family domains detected in this protein sequence.
2. Correct, It is more reliable that this gene belongs to CBM50 cazyme family.
