### ISSUE TITLE
Parameters issues

### ISSUE THREAD

**Issue by BenedicteColnet** [linnabrown/run_dbcan#7]
Hello,

I used dbCAN with the default parameters (meaning without writing the parameters values such as `--hmm_eval` in the command line ), and then I launched the same pipeline but with the default parameters explicitly mentioned and according to the default parameters you mention in your readme. The 2 results are different. Do you have an explanation ?

Thank you by advance for your help.

**Comment by linnabrown** [comment]
Thank you very much for your feedback. We will check it out as soon as possible. Before doing this, could you email us your data and command line? Thank you @yinlabniu @HaidYi @BenedicteColnet 
yyin@unl.edu
2120160409@mail.nankai.edu.cn

**Comment by BenedicteColnet** [comment]
This is the command line for the default :

''' python run_dbcan.py EscheriaColiK12MG1655.fna prok -c cluster --out_dir ../volume/Escherichia/default '''

And this is when parameters are set like default mode but explicitly : 

''' python run_dbcan.py EscheriaColiK12MG1655.fna prok -c cluster --dia_eval 1e-121 --hmm_eval 1e-35 --hmm_cov 0.35  --hotpep_freq 2.0 --cgc_dis 2 --out_dir ../volume/Escherichia/default_manual/ '''

Thank you by advance for your answer.

**Comment by linnabrown** [comment]
Thank you very much, and this is our readme TYPO 
In code run_dbcan.py, line 31, you can see the default is 1e-102, not 1e-121
```
parser.add_argument('--dia_eval', default=1e-102,type=float, help='DIAMOND E Value')
```
In line 33, default is 1e-15, not 1e-35
```
parser.add_argument('--hmm_eval', default=1e-15, type=float, help='HMMER E Value')
```
in line 37, hotpep frequent is 2.6 not 2.0.


I will ajust the default value of readme. Thank you very much!

**Comment by BenedicteColnet** [comment]
Thank you for your answer !
