### ISSUE TITLE
DIAMOND not working, HMMER and Hotpep unaffected

### ISSUE THREAD

**Issue by Itallia** [linnabrown/run_dbcan#75]
Hello,
I am using command-line to run dbcan2 on .fasta files. Under two specific conditions, DIAMOND does not work (HMMER and Hotpep still work fine): 

1. I try to output the final file to a different folder than the db.
2. I have the db folder in a cloud-based folder (linked to my computer as an external folder).

The error returned is:

`Computing alignments... Device not configured .... Error writing file diamond-tmp-gwCk44`

Note the number of the diamond-tmp file changes for each attempt.

Is this an issue that can be fixed? It's making the diamond part of the database unreliable.

Thank you.

**Comment by linnabrown** [comment]
I have never met this kind of error `Device not configured`. It's maybe caused by the db folder located in a cloud-based folder.
Maybe you should check the manual from Diamond.

**Comment by Itallia** [comment]
Thanks for getting back to me so quickly. I will check the Diamond manual.
