### ISSUE TITLE
More Explanation for the CGC-finder output?

### ISSUE THREAD

**Issue by BinhongLiu** [linnabrown/run_dbcan#76]
Hi! Thank you for the great tool! I just used and cited this tool in my paper!
Now I'm confused about the output of CGC-finder.
![微信图片_20210824155700](https://user-images.githubusercontent.com/35453307/130580020-aec727c8-6f1f-4a0f-802a-e26fe0a61be5.png)

1. what are the column names?
2. Is each group separated by +++++ an individual CGC? 
3. I can see multiple CGC1 in the output. Are CGCs with the same number the same one?
Many thanks!
Best!

**Comment by linnabrown** [comment]
Thank you for using our tool.
1. the identifier of this protein. 
2. Yes
3.  Let me check this later.

**Comment by linnabrown** [comment]
We reformated CGC_Finder output and please refer to our new document. Thank you for bringing this out.
