### ISSUE TITLE
README lists incorrect argument names

### ISSUE THREAD

**Issue by acvill** [linnabrown/run_dbcan#77]
Thanks for the great tool! Small comment:

The README [currently lists](https://github.com/linnabrown/run_dbcan#params) the following arguments for Hotpep parameters

    --hot_hits
    --hot_freq
    --hot_cpu

However, the dbCAN2 driver script help file (run-dbcan v2.0.11) specifies the names for the same arguments differently

    --hotpep_hits
    --hotpep_freq
    --hotpep_cpu

Using the shorter names throws an error when calling `run_dbcan.py`.

**Comment by linnabrown** [comment]
Sorry. This inconsistence is resolved. Thanks you so much for indicating this.
