### ISSUE TITLE
error while running CGCFinder 

### ISSUE THREAD

**Issue by 1023011930** [linnabrown/run_dbcan#79]
hi dear sir or madam, 
i just run the code "run_dbcan.py Pecora1_GeneModels_AllModels_20210510_aa.fasta protein -c Pecora1_GeneModels_AllModels_20210510.gff --out_dir Pecora1_CGC --dia_cpu 30 --hmm_cpu 30 --hotpep_cpu 30 --tf_cpu 30 --cgc_dis 3"    using  an fungi  protome  "Pecora1_GeneModels_AllModels_20210510_aa.fasta"  downloaded from JGI (https://mycocosm.jgi.doe.gov/mycocosm/species-tree/tree;o-RsFx?organism=neocallimastigomycetes)   

after diamond ,  humm and hotpep, i fail . here is the error type

*****************************CGC-Finder start************************************
diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: Pecora1_CGC
#Target sequences to report alignments for: 1
Opening the database...  [0.054s]
Database: db/tcdb.dmnd (type: Diamond database, sequences: 14465, letters: 6343638)
Block size = 2000000000
Opening the input file...  [0.005s]
Opening the output file...  [0s]
......

and then 

Total time = 11.03s
Reported 1241 pairwise alignments, 1241 HSPs.
1241 queries aligned.
Traceback (most recent call last):
  File "/home/microbelab/miniconda3/envs/run_dbcan/bin/run_dbcan.py", line 391, in <module>
    notes[temp[0]] = temp[1]
IndexError: list index out of range

 
please help me to find out the problem . Thank you and i have a question "Is CGCFinder only used for prokaryotic??"

**Comment by 1023011930** [comment]
i can hand in my gff and fasta file if you need

**Comment by linnabrown** [comment]
We will update CGCFinder and please wait for our new version.

**Comment by linnabrown** [comment]
git clone https://github.com/linnabrown/run_dbcan.git
pip install run-dbcan==3.0.0
