### ISSUE TITLE
If using a pre annotated metagenome shall we use input type protein?

### ISSUE THREAD

**Issue by Lamm-a** [linnabrown/run_dbcan#80]
Hi there,

Pretty much as the title says :)

I have already annotated my metagenomes with prodigals meta pipeline so shall my input type be `protein`?

I assume input type `meta` is for unannotated metagenomes?

**Comment by linnabrown** [comment]
If you need to annotate metagenomes, you need to choose `meta` when you run the `run_dbcan.py`

**Comment by Lamm-a** [comment]
and if you have already annotated you pick `protein` ? Awesome thanks for the fast response :)

I have another question quickly:

Do the `Diamond `and `HMMscan `modules of `run_dbcan` use the `dbCAN` database, whilst the `hotpep` module uses its [own database](https://github.com/linnabrown/run_dbcan/tree/master/Hotpep/CAZY_PPR_patterns) right?

**Comment by linnabrown** [comment]
and if you have already annotated you pick protein ?
-what do you mean?
Do the Diamond and HMMscan modules of run_dbcan use the dbCAN database, whilst the hotpep module uses its own database right?

-Yes.

**Comment by Lamm-a** [comment]
I mean if I have already annotated my metagenome so have the `.faa` files, I should pick the `protein` input type?

**Comment by linnabrown** [comment]
I think so.
