### ISSUE TITLE
run_dbcan hotpep output contains non-existent EC numbers

### ISSUE THREAD

**Issue by Lamm-a** [linnabrown/run_dbcan#81]
The hotpep.out for run_dbcan contains non-existent EC numbers that seems to be a merging of multiple EC numbers, for example `3.2.1.13.2.1` which can be seen in the attached output. This seems to be a combination of `3.2.1.1` and `3.2.1.-` with the `.-` omitted.

[Hotpep.zip](https://github.com/linnabrown/run_dbcan/files/7745556/Hotpep.zip)

**Comment by linnabrown** [comment]
We are updating the new version that removing Hotpep and adding eCAMI which can also look for the subfamily. You can try the new software instead. Thank you so much and happy holiday.

**Comment by Lamm-a** [comment]
Oh cool! How come you are stopping the use of hotpep?

**Comment by yinlabniu** [comment]
We have developed a better tool called eCAMI. Others also found that hotpep's performance is not very good: https://doi.org/10.6084/m9.figshare.14370836.v1
________________________________

**Comment by Lamm-a** [comment]
Very cool stuff!! Is there an ETA on the release?

**Comment by linnabrown** [comment]
I have already updated just now. Please check the github. Also, since eCAMI could not integrated in PYPI so you had to git clone https://github.com/linnabrown/run_dbcan.git and eCAMI is integrated inside run_dbcan folder.

**Comment by Lamm-a** [comment]
Many thanks, i will try this ASAP! So it is able to get the EC level resolution similar to Hotpep right?

**Comment by yinlabniu** [comment]
That's right. Even better is that the overview file now contains a column named EC numbers (extracted from eCAMI).
________________________________

**Comment by Lamm-a** [comment]
I can't express enough how cool and thankful I am you have done this! You guys do awesome work :)

**Comment by linnabrown** [comment]
Thank you.
