### ISSUE TITLE
error when using --out_pre argument

### ISSUE THREAD

**Issue by szimmerman92** [linnabrown/run_dbcan#84]
Hi,

I am using version 3 of dbcan. When I set the --out_pre argument to EscheriaColiK12MG1655 using the sample dataset I get the following error. 

> Failed to open sequence file run_dbcan/output_EscheriaColiK12MG1655/EscheriaColiK12MG1655/uniInput for reading

However, if I don't use the --out_pre argument the tool works perfectly.

Thank you very much for making dbcan! It is very helpful.

Best,
Sam

**Comment by linnabrown** [comment]
Hi Sam,
There is no parameter caleld `--out_pre` in dbcan script. Do you mean `--out_dir`?

**Comment by linnabrown** [comment]
I don't have this kind of bug when I am using `run_dbcan EscheriaColiK12MG1655.fna prok --out_dir EscheriaColiK12MG1655`. What's your command like?

**Comment by linnabrown** [comment]
Thank you for indicating this bug. I am now fixing it.

**Comment by szimmerman92** [comment]
Hi,

Thank you very much. I saw there were some other comments left before this most recent one. My command was

`run_dbcan EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655  --out_pre EscheriaColiK12MG1655`

Sorry if there was any confusion.

**Comment by linnabrown** [comment]
`pip install dbcan==3.0.2`
