### ISSUE TITLE
Error: Error reading input stream at line 51600321: Invalid character (ASCII 0) in sequence

### ISSUE THREAD

**Issue by Betula0422** [linnabrown/run_dbcan#87]
Hi, when I used run_dbcan.py to analyze my unigene sets, I revieced this error: Error: Error reading input stream at line 51600321: Invalid character (ASCII 0) in sequence

Here is my command: python run_dbcan.py --db_dir {mypath}/db \
--hmm_cov 0.35 --hmm_eval 1e-15 --hmm_cpu 20 \
--dia_eval 1e-102 --dia_cpu 20 \
--out_dir {mypath}/dbcan2 --out_pre genemark {mypath}/unigene.fasta meta

I think that this error may be caused by spaces in the unigene.fasta, so I used this command to search the spaces in unigene.fasta: grep " " unigene.fasta. But there wasn't any space in the file.

Could you tell me what caused the error? 

Best wishes!

**Comment by linnabrown** [comment]
The ASCII code for space is 32 not 0. It shows that you have [ASCII 0](https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html) in line 51600321. You need to double check it by yourself to remove the invalid character.

**Comment by linnabrown** [comment]
https://github.com/bbuchfink/diamond/issues/333#issuecomment-597292589

a trailing whitespace?

**Comment by Betula0422** [comment]
> [bbuchfink/diamond#333 (comment)](https://github.com/bbuchfink/diamond/issues/333#issuecomment-597292589)
> 
> a trailing whitespace?

No, I have deleted the trailing whitespace in the file but this error still exists. T^T

**Comment by linnabrown** [comment]
I really have no idea what's going on. If you don't mind, you can send me your input file to me and let me check that.

**Comment by Betula0422** [comment]
> 

Thank you so much! I will try to run this code again. If the error still exists, I will send my input file to you. Thank you again for your patient answers!
