### ISSUE TITLE
ModuleNotFoundError: No module named 'dbcan.utils'

### ISSUE THREAD

**Issue by bhandari63** [linnabrown/run_dbcan#88]
I followed the step-by-step process for the installation of the new version except for SignalP installation. After the installation, when I run the code for the test file using 
run_dbcan EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655

And i get the following error

 File "/home/aubrrb/.conda/envs/dbcan/bin/run_dbcan", line 5, in <module>
    from dbcan_cli.run_dbcan import cli_main
  File "/home/aubrrb/.conda/envs/dbcan/lib/python3.8/site-packages/dbcan_cli/run_dbcan.py", line 23, in <module>
    from dbcan.utils import simplify_output, cgc_finder
ModuleNotFoundError: No module named 'dbcan.utils'

Can you please let me know what went wrong?

**Comment by linnabrown** [comment]
That sounds strange. I did not meet this problem. And we can install the pkg and run the example command line successfully in the new desktop or server.

**Comment by linnabrown** [comment]
We put a new version for Bioconda. Do you still have this problem? @bhandari63
