### ISSUE TITLE
[Errno 2] No such file or directory: 'output_EscheriaColiK12MG1655/hmmer.out'

### ISSUE THREAD

**Issue by RinaYona** [linnabrown/run_dbcan#92]
Hi,

I set up the run_dbcan in my Mac and tested using “$ run_dbcan EscheriaColiK12MG1655.faa prok --out_dir output_EscheriaColiK12MG1655”.
However, the error code was shown such as here
Traceback (most recent call last):
  File "/Users//virtualenvs/run_dbcan/bin/run_dbcan", line 8, in <module>
    sys.exit(cli_main())
  File "/Users//virtualenvs/run_dbcan/lib/python3.9/site-packages/dbcan_cli/run_dbcan.py", line 224, in cli_main
    with open(outDir+prefix+'hmmer.out') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_EscheriaColiK12MG1655/hmmer.out'

In output file, hmmer file doesn’t exist.
And the results in the other diamond, eCAMI, prodigal are not included in their own files.

Could you give me any idea?

**Comment by linnabrown** [comment]
Thank you for using our tool. How did you install this package?

**Comment by linnabrown** [comment]
run_dbcan EscheriaColiK12MG1655.fna prok --out_dir output_EscheriaColiK12MG1655

with prok prameter, you should use .fna, not .faa

**Comment by RinaYona** [comment]
Thank you for replying.
As you mention, I replaced .fna from faa and the run_dbcan worked without any trouble.
I might mistake typing.

Thanks
